### ISSUE TITLE
Bitte ein Changelog!

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#11]
Es fällt jetzt sogar mir (der ich viele Schritte direkt beobachtet habe) schwer, noch alle Änderungen nachzuvollziehen, meinst Du, Du könntest eine Rubrik Changelog in der README anlegen und pflegen?

Vielen Dank!

**Comment by mworion** [comment]
Macht Sinn. Ich werde das ins readme packen, da nicht alle die Commit Messages bzw. die History auf Git lesen werden.
Habe mal angefangen....
