### ISSUE TITLE
On -> on und Off -> off möglich?

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#12]
Zumindest für fhem sind On und Off nicht immer akzeptiert, manchmal braucht es on und off. Kannst Du die defaults daher möglicherweise auf on und off setzen anstelle von On und Off?

**Comment by mworion** [comment]
Hallo Benrd,

ist das grundsätzlich so? Es klingt so, dass es auch manchmal anders ist.
Du kannst ja schon heute einfach den Parameter ['on','off] mit übergeben.

**Comment by bgewehr** [comment]
Tatsächlich hängt es vom jeweiligen Schalter ab. Intertechno und Homematic will on off, andere akzeptieren auch On Off. Wäre nur die Idee, das die Nutzer nicht über dieses Detail stolpern... Hast natürlich Recht, dass es auch jetzt schon geht, wenn man es weiß!

**Comment by mworion** [comment]
Wenn man aber eh herausbekommen muß, wie die Systeme das brauchen, dann mache Doch einen Vorschlag, wie wir das sinnvoll im Readme mit Beispiel Konfigurationen beschreiben können. Dass stelle ich dann mit ein.
