### ISSUE TITLE
Condition for execution

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#13]
In fhem kann man Bedingungen angeben, die erfüllt sein müssen, damit ein timer ausgeführt wird.

Zum Beispiel "In der Woche nur Rolladen hoch, wenn nicht Schulferien sind" oder sowas.

Diese Conditions sind nur Texte, die für die Erstellung des WeekDayTimers in fhem herangezogen werden können. Nun überlege ich, ob diese irgendwo im UI der UZSU platziert werden können und möchte fragen, ob es so ein Konzept auch in SH.py gibt?

**Comment by mworion** [comment]
Asu meiner Sicht gibt es so ein Konzept in smarthome.py über Logiken. das sind das Python scripte, die (fast) alles steuern können. Im Backend der UZSU ist so etwas nicht vorgesehen, weil halt schon über logik umgesetzt.

**Comment by mworion** [comment]
Habe mir das Interface einmal angesehen. Da ich keine Dtaen selbst speichere und nur das definierte Dict des UZSU Plugins verwende, bekmme ich das nicht sinnvoll in das Datenmodell mit rein. Ist bei smarthome.py wie beschrieben anders gelöst.

Schließe damit den Punkt, sofern keine Ideen mehr kommen.

**Comment by bgewehr** [comment]
Nochmal hierzu:
In fhem wäre es recht leicht, Conditions zu verarbeiten.
So kann man verschiedene Basisfunktionen der Zeitsteuerung verwenden, um sehr sinnvolle Dinge zu tun:

1. Condition als Bedingung der Ausführung "jetzt nicht..."
Wird realisiert durch Attribut "delayedExecutionCond" des WeekdayTimers
Super Sache, wenn man einen Fenstersensor an der Terassentür hat: Solange der nicht auf closed steht, wird der down-Befehl verzögert. (Natürlich doof, wenn man vergessen hat, die Tür zu schließen und weggeht... ;-)) Dafür kann man sich dann aber auch nicht mehr aussperren. 

Funktioniert so, dass der zeitgesteuerte Befehl erst dann ausgeführt wird, wenn die delayedCondition auf true fällt, man also z.B. die Tür schließt.

2. Condition als Bedingung der Ausführung "ja/nein"
Dies ist etwas anders, hier kann man Bedingungen formulieren, die dann einen Befehl zulassen bzw. verhindern. Eignet sich also sehr gut für Feiertage, Ferientage (NICHT die Kinder wecken, wenn sie schlafen können...) usw. Wäre pro Zeile nötig.

Wir hatten schon darüber geschrieben, dass es in sh.py so etwas in dieser Form nicht gibt. Kannst Du Dir vorstellen, einen Usermode 99 für fhem zu integrieren, in dem solche Sachen enthalten sind? Die würden ja dann den geneigten sh.py Nutzer nicht stören, aber wir könnten ohne fork auskommen.

Alternativ wäre es interessant, mit den UZSU Plugin-Autoren mal Kontakt aufzunehmen, ob die nicht auch an sowas Interesse hätten...

Was meinst Du?

**Comment by mworion** [comment]
Hallo Bernd,
Prinzipiell ja, wichtig: das Widget muss eine Frontend bleiben, keine Auswertungen und keine ausführungslokig rein, sondern nur die Einstellungen dafür. 
Zeitmässig weiss ich nicht nicht wie es reinpasst. Erst muss 3.0 Mals fertig sein, dann muss ich nicht erst mal um einige andere Dinge kümmern.
Kannst du dafür mal eine Entwurf machen, was dort zu bedienen ist, welche Daten wie ausgetauscht werden ? Vor allem brauche ich eine Idee, wie wir das testen, denn ich kann es definitiv ja nicht mit FHEM nachstellen, weil ich es nicht einsetze. 
Michel

**Comment by mworion** [comment]
Hallo Bernd,
Kannst du mir mal sagen, woher in FHEM die Informationen für Feiertage usw. Kommen?

**Comment by bgewehr** [comment]
Es gibt ein device Holidays für die Feiertage:
http://fhem.de/commandref.html#holiday

Hier gibt es eine Beschreibung, wie man damit umgehen kann:
http://www.fhemwiki.de/wiki/Wochenende,_Feiertage_und_Schulferien

**Comment by bgewehr** [comment]
![]()

**Comment by bgewehr** [comment]
![](http://i.imgur.com/ozDyZZL.jpg)

Das sind die Elemente in Fhem, mit denen man dann in dem WeekdayTimer als Conditions arbeiten kann.

Zusätzlich gibt es auch noch $we für die Wochenenden, aber das brauchen wir hier ja nicht.

Hast Du mal bei sh.py oder dem UZSU Plugin-Autor nachgefragt, ob auch dort der Bedarf besteht, dynamisch auf Kalender oder andere device-Readings zu reagieren?

**Comment by mworion** [comment]
Danke für die Info. Sieht interessant aus.
Wegen Rückfrage: nein, ich hatte bei 2ndsky noch nicht nachgefragt. Er hatte nur zuletzt relativ deutlich gesagt, dass er aufgrund einer beruflichen Veränderung erst einmal keine Zeit mehr hat und es evt. auch wegen seinem Themenfeld Konflikte geben könnte. Es ist seither auch sehr ruhig von ihm. Da die allgemeine Aktivierung ja über Logik sehr einfach zu realisieren ist, glaube ich nicht daran, dass kurzfristig was passiert. Zu viele Lösungen schon da. In sh sind die Einzelfunktionen separat (UZSU, Kalender, Items, andere Plugins). Für den User beliebig kombinierbar. 
Insofern geht es wohl eher darum, was wir gemeinsam als Fronten sinnvoll ergänzen können. Ich würde dann versuchen darauf zu achten, dass eine Integration zumindest keine Architekturänderung benötigt.

**Comment by bgewehr** [comment]
Die Lage hat sich mal wieder verändert:

Man kann jetzt in fhem einen Werktag daran erkennen, dass !$we true ist und $we false und man kann diese Variablen im Weekdaytimer verwenden, um Zeitschaltungen zu bauen.

Damit kann man prima UZSUs bauen, die an Stelle der Weekdays (Mo Di Mi ...) nur noch zwischen $WE und !$WE unterscheiden.

Gibt es so etwas in SH auch und würde sich da anbieten, einen eigenen Mode für zu entwickeln, der nur diese beiden Tagesarten anbietet? Werktag und arbeitsfreier Tag?

**Comment by mworion** [comment]
Hallo Bernd,
Soviel ich mitbekommen habe, gibt es in SH so etwas nicht. Ich habe auch die Befürchtung, dass es mit dem Plugin auf der SH Seite nicht wirklich weitergeht. Auf der anderen Seite habe ich von der SH Seite zu dem erweiterten JSON bislang keine negativen Rückmeldungen gehört. Auf dieser Basis kann man ja weiter arbeiten. 
hab zwar im Moment wenig Zeit, sollten wir aber mal in Angriff nehmen. Kannst du eine. Vorschlag machen für den JSON Eintrag und mal wieder einen Design Konzept machen. Einzig das testen kann ich dann nicht mehr übernehmen.....

**Comment by bgewehr** [comment]
Hey super, dass Du so hilfsbereit bist, vielen Dank! Ich kann leider erst ungefähr Ende Juli damit anfangen. Wie ist das sonstige Feedback zu Sunrise und Co von der SH Seite?

**Comment by mworion** [comment]
So Zwiegestalten. Was ich verstanden habe gibt es zwischen Plugin und SH ein Architekturproblem, was dazu führt, dass bei vielen schaltuhren einige nicht ausgeführt werden. Das kann ich selbst ja nicht beheben. Der Rest ist ganz zufrieden. Wie sieht es denn in der FHEM Gemeinde aus ?

**Comment by bgewehr** [comment]
Ich habe nur eine Kritik bisher gesammelt: für einfaches ON OFF wollen einige den Flip Switch mit Text Ergebnis (on off, up down usw.) zurück haben, weil sie ihn viel intuitiver finden als den Select. Sonst alle glücklich, glaube ich, leider wie immer wenig Feedback.

**Comment by mworion** [comment]
Hatten wir das mal mit dem on Off ? Ich kann mich da eher nicht dran erinnern. Wenn ichs richtig im Kopf habe kann man für Bool sich zwar andere Texte auswählen, kommt aber immer 0/1 zurück. Wechel Werte verwendet denn FHEM für boolsche Variablen ? SH kann da mehrere 0/1 True/False Sogar on/off.

**Comment by bgewehr** [comment]
Ja, hatten wir mal: https://github.com/mworion/uzsu_widget/issues/3

Wir brauchen einen für fhem einen Flip mit wählbarer Beschriftung und dem der Beschriftung entsprechenden Ergebnis. Dem Select für zwei Werte wird ein schlechter WAF bescheinigt! ;-)

**Comment by mworion** [comment]
Sollte eigentlich leicht gehen. Schaue es mir an.

**Comment by bgewehr** [comment]
Super, danke!!

**Comment by bgewehr** [comment]
Wie wäre es, wenn wir anhand der Anzahl der Elemente entscheiden, ob wir einen Flip (=2) oder einen Select (>2) verwenden? Dann ist das generisch und immer OK..?

**Comment by mworion** [comment]
Hallo Bernd,

Danke für die Ideen. Probiere mal die v3.1 develop aus. Ich habs etwas anders gelöst. Bei Listen kannst Du ja zwischen text und Inhalt unterscheiden, wenn du explizit einen Inhalt angeben willst. Das geht jetzt auch bei Bool und dem Flip. Einfach als textparameter mit ':' getrennt den wert angeben (['1:on','0:off']). dann sollte auch on bzw. off zurück geschrieben werden. 

Michel

**Comment by bgewehr** [comment]
Klingt ja super, ich probiere es aus - dauert aber noch etwas...

**Comment by bgewehr** [comment]
So der offtopic Flip kann ja erstmal als im Test abgehakt werden - zurück zum Issue Titel.

Ich mache Ende des Monats Vorschlägenzum Design und zum JSON - OK?

**Comment by mworion** [comment]
OK, bis dahin habe ich auch kaum Zeit. Warte auf Deinen Vorschlag !

**Comment by bgewehr** [comment]
Rückmeldung aus dem fhem Forum: Erster Test des Flip erfolgreich!

**Comment by bgewehr** [comment]
Im Grunde würde für fhem folgendes reichen:
Drei Felder:
- Device
- comparator
- Value

Damit kann man dann sagen mach dies um 08:00, aber nur wenn der Wert von Device z. B. kleiner als 15 ist.

Realbeispiel: mach die Bewässerung des Gartens um 05:00, aber nur wenn die Regenprognose morgen kleiner als 1 mm/qm ist oder sowas in der Art.

Alternativ müsste man eine gültige Perl- Bedingung in ein einziges Textfeld schreiben. Das ist zwar anspruchsvoller, aber auch vielseitiger und lässt Und und oder zu...

**Comment by mworion** [comment]
Das heist unter dem Strich, es kommen in das dict weitere 3 Werte rein mit
device (string)
comparator (string)
value (string)
korrekt ?
Länge der Strings in Zeichenzahl ?
Diese würde ich dann unter einer Auswahlliste wählen lassen, die als Parameter in der Visu wie bei den Werten übergeben wird. Die Parameter werden an die bestehende USZU Parameter angehängt.

**Comment by mworion** [comment]
Ach ja: und bitte für alles einmal Beispiele mit den extremen Situationen

**Comment by mworion** [comment]
...zum Design:

Kannst ja mal unter http://jsfiddle.net/mw_orion/2sv5Lo5k/#&togetherjs=GE1cglk8ek 
etwas probieren :-)

**Comment by bgewehr** [comment]
Super Vorlage! Gib mir bitte Zeit bis Anfang August! Vorher schaffe ich es nicht...

**Comment by mworion** [comment]
Kein Problem

**Comment by bgewehr** [comment]
Ich habe mal gebastelt:
http://jsfiddle.net/mw_orion/2sv5Lo5k/#&togetherjs=GE1cglk8ek

**Comment by bgewehr** [comment]
Sorry, falscher link:
http://jsfiddle.net/mw_orion/2sv5Lo5k/#&togetherjs=GE1cglk8ek

**Comment by bgewehr** [comment]
Sorry, falscher Link:
http://jsfiddle.net/2sv5Lo5k/3/

**Comment by bgewehr** [comment]
Oder nochmal mit act-checkboxes?
http://jsfiddle.net/2sv5Lo5k/4/

**Comment by mworion** [comment]
Hallo Bernd,

nachdem das Widget in der 3.99 als Release Cadidate (responsive)  auf smartvisu v2.8 mit sag umgestellt ist, wollte ich auch die Condition mit Dir zusammen fertig machen. Deine Beispiele gefallen mir gut. 
Ich hatte verstanden, dass es nur um die Eingabe der Condition mit den drei Feldern (oder 4 wenn es act gibt) geht. 
Gib mir doch einfach mal die Definitionen, wie ich die in das JSON reinpacken sollte. Wie sollen heißen? Vorschlag:

fhem_device (string) (alles)
fhem_comparator (string) ('>','<','=','>=','<=')
fhem_value (string) (alles)
hem_act (string) -> (true, false, 0,1)

Welche Values wären dort erlaubt ?

Grüsse

Michel

**Comment by bgewehr** [comment]
Gib mir 2-3 Tage bitte!

**Comment by mworion** [comment]
Kein Problem, aber es wird etwas Zeit geben, da könnten wir das FHEM Thema etwas vorantreiben

**Comment by mworion** [comment]
aktuell v3.99rc1 mit Deinem Fiddle in der Oberfläche (allerding ohne technische Funktion)

**Comment by bgewehr** [comment]
Habe es geladen und ausprobiert.
![2015-12-01 22_03_43-start](https://cloud.githubusercontent.com/assets/4056277/11514226/9f7c34f4-9877-11e5-841a-9720b40cf9d3.png)

Super, sieht gut aus.
Warum ist der feine Rahmen nur um die Sunrise-Elemente? Sollen die Conditions Elemente final auch da rein oder eigener Rahmen?
Ich frage noch mal im fhem Forum nach, dann gebe ich Dir Bescheid...

**Comment by mworion** [comment]
Bernd,

Du must auch das Widget.html ersetzen, weil dort die .css Einstellungen für die Rahmen drin sind.

**Comment by bgewehr** [comment]
Habe ich gemacht. Vielleicht habe ich noch im css-file eigene Formate, muss ich prüfen.

Von der Logik her würde ich jetzt sagen, dass dann die Sunrise-Zeile auch ein act button haben sollte und die Auswahl "time" entfällt. Nur noch rise and down. active = Zeiteingabe inactive, Sunrise-Elemente active und andersherum. Wäre dann sehr transparent zu verwenden, was meinst Du?

**Comment by mworion** [comment]
Stimme Dir da zu, schaue ich mir an.

**Comment by bgewehr** [comment]
Bisher gibt es nur zwei Antworten aus dem Forum. Beide eher von Fortgeschrittenen. Sie bevorzugen ein einziges Feld für Perl-Ausdrücke, die fhem als String übergeben werden und dann dort evaluiert werden können.

Ich bin der Meinung, dass man das leicht abbilden kann, indem man Logik benutzt:

WENN Feld1 gefüllt, Feld2 aber nicht, dann ist es wohl ein Perl-Ausdruck, wenn nicht, ist es ein Vergleich von Device und Value. 

Kann ich im Code leicht so verarbeiten.

Ok für Dich?

**Comment by bgewehr** [comment]
stups...

**Comment by mworion** [comment]
Hallo Bernd,

sorry bin nach wie vor Land unter, versuche aber mal weiter zu machen. Vorschlag für die Erweiterung des Datenmodells im JSON:

// Datenmodell: Austausch über JSON Element
//              {   "active"    : bool, 
//                  "list"      :                   Liste von einträgen mit schaltzeiten
//                  [   "active"    :false,         Ist der einzelne Eintrag darin aktiv ?
//                      "rrule"     :'',            Wochen / Tag Programmstring
//                      "time"      :'00:00',       Uhrzeit des Schaltpunktes
//                      "value"     :0,             Wert, der gesetzt wird
//                      "event":    'time',         Erweiterung zur Laufzeit: Zeitevent oder SUN
//                      "timeMin"   :'',            Untere Schranke SUN
//                      "timeMax"   :'',            Oberere Schranke SUN
//                      "timeCron"  :'00:00',       Schaltzeitpunkt
//                      "timeOffset":''             Offset für Schaltzeitpunkt
//                      "FHEM"      :   {
//                                          "conditionActive"   : bool
//                                          "conditionDevice"   : text
//                                          "conditionType"     : text
//                                          "conditionValue"    : text
//                                      }
//                  ] 
//              }

im Device wäre dann auch der Textstring drin. Alternative: FHEM entscheidet vorab, wie man einegeben soll, dann kommt halt ein bool element dazu, was die Eingabelogik festlegt.

**Comment by mworion** [comment]
Mir ist noch etwas einfacheres eingefallen:
beim Condition type gibt es einfach zusätzlich den Eintrag "PERL", damit legt es einfach der Nutzer fest !

**Comment by bgewehr** [comment]
Ja, soweit gut!
Ich schlage vor, es nicht FHEM zu nennen, sondern Condition weil ja auch alles andere in fhem verwendet wird.
Was wir noch brauchen ist die Festlegung, ob dieser Bereich erscheinen soll, oder nicht, also einen fhem true false Parameter für das UI. Bei nicht-fhem kann das ja verborgen bleiben...

**Comment by bgewehr** [comment]
Ja, das ist gut so. Ich weiß allerdings schon, was dann kommt: 

Wenn perl true, dann Feld value bitte weg und Feld device größer...

**Comment by bgewehr** [comment]
// "Condition" : {
 // "conditionActive" : bool
 // "conditionDevice" : text
 // "conditionType" : text (selection {">","<","==","<=",">=","!=","Perl"})
 // "conditionValue" : text

**Comment by bgewehr** [comment]
Freu mich schon auf neue Tests!
Dank Dir, dass Du den Faden wieder aufnimmst...

**Comment by mworion** [comment]
Das mit FHEM ist soweit OK nennen ich Condition
Einen FHEM Parameter nehme ich nicht auf, wenn Condition im JSON String drin ist, kommt einfach dieser Menüanteil, bei smarthome ist er nicht da, dann entfällt das menü
Die Feldlängen passe ich mal an entsprechend der Benennung. 
Ja die Frage wird kommen, schauen wir mal

**Comment by mworion** [comment]
Hallo Bernd, auf github gibt es ein repo responsive_develop, dort ist eine variante zum test eingecheckt. Probiere das mal aus.
der JSON String ist im Header beschrieben. 
die condition zeilen müssen bereits enthalten sein, sie können nicht durch die visu erzeugt werden !
dort wo (das geht sogar pro zeile) eine condition vorhanden ist, geht der experte auf rot und du kannst die felder editieren und zurückschreiben.

bin gespannt was du erlebst.

im visu.js ist von mir eine testzeile enthalten, die einen JSON eintrag mit den daten erzeugt. Das ist meine einzige testmöglichkeit.

**Comment by bgewehr** [comment]
Bin dabei zu testen.
Gar nicht so einfach, weil bisher keine Komponente am JSON String modifiziert hat außer der visu.

Nun muss fhem oder fronthem die nötigen Optionsparameter in den jSON string einbringen, da muss ich erst sehen, wie das geht.

Dass man die conditions Zeile im JSON nicht einfach erzeugen kann durch einblenden verstehe ich, sonst neue Displaytype nötig. smarthome braucht das ja nicht. 

Allerdings fände ich das inzwischen sogar passend, weil ein displaytype fhem sofort die we und die condition beinhalten könnte und nicht erst umständlich unterwegs den JSON String modifizieren muss. Andererseits ist der displaytype 1 vielleicht inzwischen überflüssig? Dann bleiben vielleicht nur noch zwei übrig...

Nochmal zurück auf ein Zitat von oben:
Von der Logik her würde ich jetzt sagen, dass dann die Sunrise-Zeile auch ein act button haben sollte und die Auswahl "time" entfällt. Nur noch rise and down. active = Zeiteingabe inactive, Sunrise-Elemente active und andersherum. Wäre dann sehr transparent zu verwenden, was meinst Du?

**Comment by mworion** [comment]
Der Hinweis auf den einen Design type hin, da werde ich einmal eine Umfrage starten, wer den benutzt. Evt. kann ich den dann entfallen lassen. Sollte ich ohnehin einmal machen.
Wenn Du nicht weiter kommst mit der JSON Erweiterung, dann sollten wir uns nochmal abstimmen. Mit FHEM als Kennung könnte ich den JSON natürlich zwingend erweitern, dann aber bei allen UZSU Einträgen und bei jeder Zeile. 

Die Anpassung mit Time usw. schaue ich mir mal an, klingt logisch.

**Comment by bgewehr** [comment]
![2016-03-06 15_13_13-starten](https://cloud.githubusercontent.com/assets/4056277/13554666/34819996-e3ae-11e5-987d-7abbae6b7fec.png)
So sieht es nun aus, wenn ich die Testzeile einschalte.
Ich versuche mich mal an einem etwas geänderten Layout:
- act button bei beiden expert-lines
- dropdown bei sunrise ohne time (weil ja nun act entscheidet, was zählt)
- perl-Feld-cell 100% und value-Feld-cell display:none, wenn dropdown = perl

Mal sehe, wie weit ich komme...

**Comment by bgewehr** [comment]
Nun mal mit smartVISU 2.8 probiert.
Ich dachte bisher immer die jquery-Darstellungsfehler lägen an der veralteten SV-Version.
Ist aber wohl nicht so:
![2016-03-06 15_30_19-starten](https://cloud.githubusercontent.com/assets/4056277/13554735/7cef37e0-e3b0-11e5-9980-6b467c490788.png)
Achte auf die expert-Buttons!

**Comment by bgewehr** [comment]
Auf dem iPhone sieht es korrekt aus:
![](http://i.imgur.com/lNPFgtr.jpg)

**Comment by mworion** [comment]
Ich habe auf iPad, Safari und Firefox, da ist es OK. Komisch.

**Comment by bgewehr** [comment]
Liegt vielleicht am Edge Browser von Windows 10, ich prüfe mal systematisch durch...

**Comment by mworion** [comment]
Es gab schon im smartvisu Forum einmal einen Hinweis, dass mit dem Edge Browser etwas nicht ganz funktioniert. Ich habe eine Windows 10 Installation, dort probiere ich auch mal die Visu aus.

**Comment by mworion** [comment]
BTW: wie sieht es mit der funktionalen Anbindung aus ? klappt das ?

**Comment by bgewehr** [comment]
Also für mich gestaltet es sich schwierig, den String unterwegs zu beeinflussen. Wir initialisieren auf fhem Seite mit {}, alles andere lassen wir die Visu liefern. Der String aus dem Test kommt aber korrekt an und könnte nun in fhem verarbeitet werden. 

Wenn's nach mir ginge, wäre eine displaytype fhem immer noch lieber, die dann über die sichtbaren Konfigurationen für Inhalte im String sorgt. Die Transporter unterwegs sollten eigentlich nur Transporten...

**Comment by mworion** [comment]
Ok, mit dem String und {} meinst du den Wert für den Eintrag z.B. Conditon oder den gesamten JSON ?

**Comment by bgewehr** [comment]
Den gesamten JSON initialisieren wir mit {} und rufen dann die Visu auf, stellen was ein und der transporter schiebt den String zurück nach fhem ohne ihn zu ändern. In fhem wird der JSON String an einem Device Reading persistent gespeichert. Ein notifier springt dabei an und erzeugt entsprechende Weekdayplaner, die die Schaltaufgaben ausführen.

**Comment by mworion** [comment]
Aber wenn ihr die Visum ein zweites Mal aufruft, dann schickt ihr doch eine aus der persistenten Speicherung generierten JSON oder ?

**Comment by bgewehr** [comment]
Der String bleibt in der ganzen Zeit unverändert gespeichert. Er wird nur zurückgeschickt an die Visu und geändert wieder empfangen und gespeichert.

**Comment by mworion** [comment]
Soweit verstanden, dann hänge ich noch daran, warum nur ein leerer String beim ersten Mal initialisiert werden kann und nicht irgendwas anderes. Muss ja nicht vollständig sein.

**Comment by bgewehr** [comment]
Weil das per Usereingabe manuell erfolgt und das nicht zu schwierig sein darf.

Ein besserer Grund fällt mir nicht ein...

**Comment by mworion** [comment]
Im Sinne einer Konfiguration richtig ?

**Comment by bgewehr** [comment]
Unsere User legen einen Switch an, sagen wir vom Typ FS20. Dann muss man sowas eingeben in die fhem Kommandozeile:

Define MeineLampe FS20 Parameter Parameter usw

Danach muss er setreading MeineLampe uzsu {} eingeben.

Was müsste er denn nun eingeben statt {}, damit Dein Plan funktioniert?

**Comment by mworion** [comment]
Wie wäre es mit {FHEM} beim Start der Initialisierung. Ich könnte das feststellen, und dann entsprechend reagieren. Kannst Du feststellen, was dann bei der VISU ankommt. Ich würde jetzt erwarten, dass im JSON ein Eintrag FHEM enthalten ist, dessen Wert Leer ist, also so {FHEM: ''}
Was aber bleibt, wenn ich die Werte belege (erstelle), dann kann ich nicht unterscheiden, bei welchen Zeilen eine Condition eingegeben werden soll und bei welchen nicht. Damit kann ich nur allen Zeilen diese Eigenschaft verpassen. 
Wäre das für Euch ein Problem ?

**Comment by bgewehr** [comment]
Alle Zeilen finde ich gut. Leere Conditions stören ebensowenig wie leere Sunrises.
{fhem:''} lässt sich sicher machen, aber bleibt das dann auch erhalten? Sonst weißt Du es ja beim zweiten Mal schon nicht mehr. Ist dann doch ein Displaytype, oder?

**Comment by mworion** [comment]
Ja im Grunde ist es dann der Display Type. Wenn keine es auslöscht (Du hattest ja geschrieben, dass die Persistenz alles speichert, dann passiert auch nichts (sofern ich es nicht aus versehen lösche).

**Comment by bgewehr** [comment]
Stimmt. Wenn Du also den Fhem Hinweis lieber im JSON haben willst als in der Widget-Defintion im Display Type, dann kann man das auch machen. Allerdings sehe ich für alle bisherigen Nutzer eine gravierende Migrationshürde: alle bestehenden jSON Strings müssten manuell mit coditions versehen werden, das werden die Nutzer nicht schön finden. Alles in allem: ich plädiere für einen Display-Type fhem, der nicht im JSON, sondern im Widget definiert wird wie bisher. Alle fhem Zeilen haben Sunrise und condition, wenn leer, dann egal, wenn nicht Act dann auch egal. Ansonsten werden sie vom Code den das notify aufruft ausgewertet und die passenden WeekdayTimer definiert.

**Comment by bgewehr** [comment]
Stimmt ja nicht, man müsste fhem:'' einfügen. Ist aber in fhem nicht so einfach wegen der Perl Analyse werden die ; in der rrule immer als Ende interpretiert und müssen beim manuellen anpassen eines jsons immer verdoppelt werden, also echt unhandlich.

**Comment by mworion** [comment]
OK, dann machen wir einen display type für FHEM. Allerdings nicht für beide heutigen Varianten, sondern nur für die eine. Aufbau identisch, nur das flag für FHEM ja / nein.

**Comment by bgewehr** [comment]
Ja, das ist glaube ich die beste Lösung. Am einfachsten für die fhem Nutzer, nicht störend für die Smarthome Nutzer, perfekt!

**Comment by mworion** [comment]
OK, ich schaue mal, wie ich es hinbekomme.

**Comment by bgewehr** [comment]
👍🔝

**Comment by mworion** [comment]
Hallo, in der version 4.2 sollte der designType = '2' für fhem funktionieren. Teste mal, ob es so geht.

**Comment by bgewehr** [comment]
Du bist ein Held!
Works like a charm!
![image](https://cloud.githubusercontent.com/assets/4056277/13725259/ad854214-e89c-11e5-860b-95146df4574c.png)
![image](https://cloud.githubusercontent.com/assets/4056277/13725260/ada50856-e89c-11e5-8b88-cd7292184463.png)

Alter String rübergegeben, in der Visu geändert, neuer String zurück.

Habe jetzt erstmal die Funktion zu ändern, mit der die Conditions ausgewertet werden können.

Starke Leistung, danke!

**Comment by bgewehr** [comment]
Das mit dem jetzt immer roten expert Button gefällt mir noch nicht optimal, Kontrast zum Orange irgendwie zu groß. Aber nicht wichtig, nur CSS.

Muss jetzt noch mal mit einem ganz leeren String testen...

**Comment by mworion** [comment]
Hallo,

der expert button hat jetzt die aktiv farbe des jquery themes, wie auch bei all den anderen. ich habe herausgefunden, wie das geht. damit nicht mehr im CSS enthalten.

**Comment by mworion** [comment]
Das responsive Design muss ich mir dann nochmal anschauen und etwas optimieren, damit es sinnvoll auf Smartphones geht. Ist im Safari jetzt sehr gut zu testen.

**Comment by mworion** [comment]
Soweit aktueller Stand eingewcheckt. mache auch diesen Thread zu. 
Bitte neuen aufmachen für bugfixing oder neuen requests.
