### ISSUE TITLE
Popup im Popup?

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#14]
Stell Dir eine geöffnete UZSU vor mit num als Typ. Nun tippt oder klickt der User auf das value-Feld und es wird überlagert mit einem popup-Slider für den Wert im gültigen Wertebereich.

Klickt man auf die Zeit, wird das Feld überlagert mit einem Time-picker, der auch die Sunrise/down settings hat.

Denkbar? Sinnvoll oder Quatsch?

**Comment by mworion** [comment]
Popup im Popup ist beim aktuellen eingesetzten Stand jquerymobile nicht darstellbar. 
Es gibt zwar Erweiterungen als Plugins für das Framework, die das dann können (nur mal drübergelesen), 
aber dann verändere ich das Framework. :-(

**Comment by mworion** [comment]
Habe keine Lösung mehr gefunden, mache den Punkt jetzt zu
