### ISSUE TITLE
Fehlerhafter Parameter "undefined" im Feld customFormat bei Item "irgendwas"

### ISSUE THREAD

**Issue by loeserman** [mworion/uzsu_widget#15]
Hallo,
das Widget ist super aber leider erhalte ich immer zwei Fehlermeldungen beim Öffnen. 

Fehlerhafter Parameter "undefined" im Feld customFormat bei Item "R33.LICHT.SCHRANK_UZSU"
Fehlerhafter Parameter "undefined" im Feld customType bei Item "R33.LICHT.SCHRANK_UZSU"

Ich habe die Stelle zwar in der visu.js gefunden aber bin da nicht so firm, wieso die Fehlermeldung kommt. Es schenit so zu sein, dass die Zuweisungen 
customFormat[0] = $(this).attr('data-customFormat');
customFormat[1] = $(this).attr('data-customType');
bei mir nicht an die richtigen Daten kommen.

Das Widget wird dennoch nach den Fehlermeldungen korrekt angezeigt und die Einstellungen darin werden auch ausgeführt. Ich habe es mit dem Firefox und dem Chrome Browser ausprobiert. Beide liefern bei mir die Fehlerbox. Habt ihr einen Tipp, was ich falsch eingestellt habe?

smartvisu.conf
```
[R33]
  [[LICHT]]
    [[[SCHRANK]]]
      name = R33 Lampe (Schrank)
      type = bool
      visu_acl = rw
      knx_dpt = 1
      knx_listen = 2/7/37
      knx_send = 2/0/37
      knx_init = 2/7/37
      [[[[UZSU]]]]
        type = dict
        uzsu_item = R33.LICHT.SCHRANK
        cache = True	
        visu_acl = rw
```

Aufruf in der HTML Datei
```
{{ widget_uzsu.uzsu_icon('uid1410231502test_uszu1', 'R33.LICHT.SCHRANK.UZSU', 'Schranklampe', '2', '', '', 'bool', ['On','Off']) }}
```

Der Versuch den designType zu ändern auf 0 oder 1 hat keine Änderung bezüglich der Meldung gebracht.

Ich habe bestimmt etwas ganz einfaches übersehen.

Danke euch schonmal.

Gruß
loeserman

**Comment by mworion** [comment]
Hallo,

bitte schaue einmal, ob nach dem letzten Update auf größer v1.5 auch die Datei widget_uzsu.html mit im Update hattest. Es gab einen Bruch bei den Parameter Namen, weil die mittlerweile durch den Feature Aufwuchs zwischen HTML und JS auseinanderliefen.
Korrekt wäre eine widget_uzsu.html v1.6 und eine visu.js v 1.71

Grüße Michel

**Comment by loeserman** [comment]
Ah wunderbar, habe nun den Fehler gefunden. Wie schon richtig vermutet war die Version in meiner visu.js Datei veraltet. Ich habe versehentlich die v1.7.1 dazu kopiert aber die alte Version war auch noch vorhanden. Somit wurden dann die alten Funktionen anstatt der neuen aufgerufen.

Super, vielen Dank für den Tipp. Hat geholfen.

Gruß
loeserman

**Comment by mworion** [comment]
Super, dann viel Spaß !
