### ISSUE TITLE
valueType num - Schritte

### ISSUE THREAD

**Issue by fhainz** [mworion/uzsu_widget#20]
Hallo!

Wäre es möglich die Schrittlänge beim valueType num konfigurierbar zu machen?

Grüße

**Comment by mworion** [comment]
Kann ich leider nicht sagen, hatte es mir noch nicht angesehen. Aus dem Bauch heraus ist die Schrittweite ganz unten in den Browser Fähigkeiten verpackt. Dort zu ändern würde das Framework ändern.
Ist im Moment nicht auf der Roadmap drauf.

**Comment by fhainz** [comment]
Die Schrittweite kann man im input mit zB step='0.5' anpassen. 
Hab das kurz getestet, das hoch/runter zählen funktioniert. Das ganze nach einem Update einfügen wäre auch nicht das große Problem.

**Comment by mworion** [comment]
Das klingt ja gut. Funktioniert das über die verschiedenen Browser gleichartig ? Wäre super, dann kommt es auf die Liste der Funktionen mit drauf, der Parameter muss ja übergeben werden und ich brauche eine rückwärtskompatible Variante. jede idde willkommen.

**Comment by mworion** [comment]
Probiere mal die aktuelle v2.8 auf dem feature branch aus. War einfacher als ich gedacht hatte. Wird wir folgt gemacht: du kannst die Parameter bei input direkt im Parameter String eingeben (sieh Beispiel). Bitte mal auf verschiedenen Browsern ausprobieren !

{{ uzsu.uzsu_icon('eg.ez.decke.12a', 'rechner.test.uzsu', 'Esszimmerlampe', '0','','','num',['step = 0.1 min = 0']) }}

**Comment by fhainz** [comment]
Funktioniert. Danke!
Getestet mit Safari, Firefox und Chrome unter OS X.

**Comment by fhainz** [comment]
Das input könnte man vielleicht noch etwas größer machen. Die Kommastelle wird derzeit (halb) abgeschnitten.
![value](https://cloud.githubusercontent.com/assets/2659971/6855391/0941a18e-d3f8-11e4-9af8-ae9ea7a983fa.png)

**Comment by mworion** [comment]
Ich habs mal auf 50px gesetzt. Aber das kannst Du selbst anpassen Zeile 173, wird im fertigen Release 3.0 in .css anpassbar sein.

**Comment by fhainz** [comment]
Danke!

**Comment by fhainz** [comment]
Sorry, ich hab schlecht getestet :( 

Zeile 394:
response.list[numberOfRow].value = parseInt($('#uzsuEntryValue'+numberOfRow).val());

Durch das parseInt() wird der Kommawert abgeschnitten.

Ich hab bei mir Zeile 390 in
if ((valueType == 'text') || (valueType == 'list') || (valueType == 'num')) {
geändert. Nun funktioniert es.

**Comment by mworion** [comment]
Danke für die Rückmeldung, dafür ist das Testen ja da.
...ist aber nicht die richtige Lösung, muss ich mir nochmal ansehen, weil das parseInt ursprünglich nur für num da war und das hast Du jetzt komplett herausgenommen !

**Comment by mworion** [comment]
...v2.91 sollte das jetzt korrekt lösen (ganz ohne Fallunterscheidung !)

**Comment by fhainz** [comment]
Funktioniert! Danke!
