### ISSUE TITLE
Dafault anstatt [On, Off] bei List

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#21]
Hallo, ich habe "Default" und "0" als Auswahl bei 'list' ohne eigene Liste. Irgendwas muss also bei der "Default"-Liste falsch laufen...

**Comment by mworion** [comment]
Ist schon richtig so eingetragen. Was soll ich denn bei einer Auswahlliste in Widget eintragen, wenn Du keine angibst ? Ich kann auch "Die Liste fehlt" hinschreiben :-)

**Comment by bgewehr** [comment]
Im früheren Code gab es den Default On, Off. Macht nix, habe ich jetzt überall geändert, also für mich OK!

**Comment by mworion** [comment]
Sorry, war so. Aber für das release muß ich die Fehlerabfrage einbauen. Es war eingentlich aus reinem Zufall ein gültiger Wert, hätte auch schief gehen können.
