### ISSUE TITLE
uzsuExpandTimestring führt bei "07:00<sunrise" zum Fehler Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#22]
V2.91
in Zeile 97:
	            if(event.indexOf('sunrise')===0) event = 'sunrise'; else event = 'sunset';

Ich blicke den Code im Moment noch nicht, daher von mir aktuell kein Hinweis auf Ursachen... ;-(

**Comment by mworion** [comment]
Hallo, ich bekommen den Fehler zwar nicht nachgestellt (weil ich wahrscheinlich keine neuen UZSU erstelle, sondern immer alte weiterverwende).
Aber formal kann event genutzt werden, bevor initialisiert. Das würde passen, daher v2.92 bitte mal ausprobieren, aber genau so wie Du den Fehler
erzeugt hast (z.B. neuen UZSU usw.)

**Comment by bgewehr** [comment]
Mit 2.92 konnte ich diesen Fehler nicht nachstellen!

**Comment by mworion** [comment]
OK, dann würde ich ihn schliessen, schaue mir aber die Portierung nochmal in Summe um !
