### ISSUE TITLE
Problem, wenn UZSU extern eingeschaltet wird

### ISSUE THREAD

**Issue by loeserman** [mworion/uzsu_widget#24]
Hallo zusammen,
ich bin begeistert von dem Plugin. Leider verstehe ich nicht ganz wie es genau funktioniert. Ich möchte es dazu verwenden die Rolläden automatisch zu steuern, wenn ich das Haus verlasse. Hierzu habe ich mir ein Skript gebaut, welches alle UZSU Objekte aktiviert und deaktiviert.

```
# Jalousie WC
value = sh.R13.ROLLO.POSITION.UZSU()
value['active'] = setval
sh.R13.ROLLO.POSITION.UZSU(value)
```
gefunden auf: http://knx-user-forum.de/forum/supportforen/smartvisu/34098-uzsu-widget/page15

Wenn ich nun Zeiten eintrage während das UZSU inaktiv ist und diese mit Save&Exit speichere, dann werden sie jedoch nicht ausgeführt, wenn das Skript die UZSU aktiv schaltet.

Beispiel:
1. UZSU deaktivieren
2. Im UZSU neue Zeiten eintragen
3. Zeiten per Save&Exit abspeichern
4. Zeiten nochmal durch erneutes Öffnen des Widgets prüfen -- alles okay
5. Bis hier hin in das UZSU noch inaktiv
6. UZSU über das Skript oben einschalten
--> Die Aktionen werden nicht ausgeführt.
--> Ohne Reload der SmartVISU Seite werden die Uhrsymbole auch nicht als aktiv dargestellt. Nach dem Reload dann schon.

Wie kann ich das lösen? Wird der Scheduler überhaupt auf diese Art und Weise mit den Daten versorgt? Gibt es einen Workaround? 
Ich habe es mit der Version 1.71 als auch 2.92 (beta) probiert. Leider funktioniert es bei beiden nicht in der Form wie ich es gedacht habe. Vielleicht denke ich aber auch verkehrt.

Vielen Dank im Voraus für die Rückmeldung.

**Comment by mworion** [comment]
Toll,  dass es gefällt. Allerdings bist Du hier im Widget, welches nur die Einstellungen macht, nicht die eigenntlichen Schaltaktionen. 
Das Widget schreibt die Daten wie Du auch in das Dictionary der Items, die das Plugins auswertet.
Die eingentliche Schaltfunktion wird im Plugin ausgeführt bzw. der Scheduler gesetzt. 
Die Anleitung Plugin und Widget zum Start ist bei https://github.com/mknx/smarthome/wiki/UZSU-(Universelle-Zeitschaltuhr) zu finden.
Bitte Deine Frage in den UZSU Plugin Thread einbringen (nicht UZSU Widget). Aus meiner Sicht kann es daran liegen, dass so etwas wie enforce update fehlt. Aber ich bin mir nicht sicher.

Es wäre super, wenn Du Deine Fragen im Forum postest, weil es sonst nciht alle mitlesen (und dann auch helfen können).

**Comment by loeserman** [comment]
Dein Tipp hat geholfen, wie auch schon das letzte Mal.
Das "enforce_updates = True" hat geholfen. Nun läuft es so wie erwartet.
Vielen Dank. 

Habe es auch im Forum gepostet.
