### ISSUE TITLE
Responsive design for Smartphones

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#25]
Für das responsive design müsste die Tabelle auf Divs umgestellt werden, die dann per mediaqueries im css formatiert werden.

Ich hab jetzt länger drüber nachgedacht und glaube, dass es dafür nötig ist, die weekdays an den Anfang zu stellen, damit man ihnen per CSS die float:left Eigenschaft entziehen kann, wenn es zu schmal wird. Es ist nämlich wohl nicht möglich, die Reihenfolge der Objekte dynamisch zu ändern, damit die weekdays en block über den anderen Objekten erscheinen, aber dazwischen, wenn genug Platz ist.

Was meinst Du?

**Comment by mworion** [comment]
Wenn die V3 mal fertig ist, mache ich mich auf jeden Fall dran die Table auf Div umzustellen, allein um Zukunftsfähig zu sein. Das gibt uns ja dann die Chance etwas herumzuprobieren.

**Comment by bgewehr** [comment]
OK! Kann ich im Moment was helfen?

**Comment by mworion** [comment]
Hallo Bernd,

irgendwie war es zu heiß heute, da habe ich mal das design umgebaut. wenn du Zeit hast kannst Du einmal den branch responsive v3.2 installieren. Bitte das widget_uzsu.html zwingend mit ! Lass Dich mal überraschen !

Michel

**Comment by bgewehr** [comment]
Super! Sieht gut aus!![](http://i.imgur.com/yVTQtmN.jpg)![](http://i.imgur.com/cCD9ENS.jpg)

**Comment by bgewehr** [comment]
Ob die weekdays am Anfang wohl noch besser aussehen als am Ende? Mal probiert?

**Comment by mworion** [comment]
Mal die nächste Version ausprobieren ! Bitte auch mal andere Werte Valuetypen und auch Browser testen. designType = 1 geht nocht nicht !

**Comment by bgewehr** [comment]
Bin unterwegs ein bisschen eingeschränkt, aber ich probier's aus so gut es geht!

**Comment by bgewehr** [comment]
Gefällt mir persönlich noch besser.

Bool und num bei mir einwandfrei, aber sowohl auf Chrome für iOS als auch bei Safari für iOS folgender Fehler:
![](http://i.imgur.com/CLDLqBZ.jpg)

Und bei List hochkant:
![](http://i.imgur.com/THCsboa.jpg)

Zum Expert:
Ich würde eine Zeile beginnend links erwarten, auf Rahmen kann ich meistens verzichten, es sei denn, sie umschließen die ganze Gruppe. Passt hochkant die Zeile Expert nicht hin? IPhone 6 würde passen, aber iPhone4 nicht?

Über "Expert" müssen wir nochmal nachdenken. Ist eigentlich nicht Expert sondern conditions, nämlich abhängig vom Sunrise oder Set.

Die häufige Wiederholung der Überschriften frisst viel Platz, erscheint mir aber auch nötig zu sein. Die Abstände innerhalb der Gruppen können noch etwas feiner werden.

**Comment by bgewehr** [comment]
Vielleicht brauchen nicht alle Felder eine Überschrift:
Weekdays kann wegfallen, ist klar.
Act und del auch, steht drauf usw.

Macht es vielleicht übersichtlicher?

**Comment by bgewehr** [comment]
Vielleicht auch noch möglich:
Statt UZSU activ einfach nur active
Statt add entry einfach nur new
Statt sort time einfach nur sort
Statt save and Close einfach nur ok

Spart soviel Platz, dass dann alles in eine Zeile passen müsste

**Comment by bgewehr** [comment]
Vielleicht auch noch möglich:
Statt UZSU activ einfach nur active
Statt add entry einfach nur new
Statt sort time einfach nur sort
Statt save and Close einfach nur ok

Spart soviel Platz, dass dann alles in eine Zeile passen müsste

**Comment by bgewehr** [comment]
Kleiner typo bei earliest: ealiest

**Comment by mworion** [comment]
iOS Fehler sehe ich bei mir nicht. komisch.
Die expertenzeile mache ich erst fertig, wenn die conditions drin sind.
Typo auch korrigiert
Habs mal wie Dein vorschlag war vereinfacht. Sieht jetzt extrem schlicht aus.
Ich packe es mal in das smartvisu forum. mal sehen....

**Comment by bgewehr** [comment]
Hast Du ins responsive gepusht? Ich bekomme already up to date...

**Comment by mworion** [comment]
Ist jetzt v3.3

**Comment by bgewehr** [comment]
Find ich super!
Je weniger erklärende Elemente nötig sind, desto klarer scheint das Design.

Missverständnisse kann es bei Type Int geben, weil hier die zwei Eingabefelder für Value und Time gleich aussehen. Rest ist aber klar, denke ich.

Funktionsbuttons finde ich super so, klar und einfach.

Die Abstände könnte man innerhalb der Gruppen kleiner machen als zwischen den Gruppen, um die Gruppenzusammengehörigkeit besser erkennbar zu machen.

Die Fehler im Expert sind geblieben. Der Fehler bei Type Text ist weg. 
![](http://i.imgur.com/CxH4DIk.jpg)

Welches iOS Device nutzt Du zum Test?

**Comment by bgewehr** [comment]
Wie immer Geschmacksache, aber auch schick:
![](http://i.imgur.com/4YEZPq7.jpg)

**Comment by mworion** [comment]
Habe jetzt noch etwas getuned noch in der v3.3. damit würde ich den Punkt grundsätzlich zumachen. Falls Fehler passieren, kommt es auf einen neuen Issue

**Comment by bgewehr** [comment]
Nur noch zum Abschluss:

Sieht bei mir perfekt aus und ist unmissverständlich:
![](http://i.imgur.com/w32xpuR.jpg)
![](http://i.imgur.com/YzMWbZO.jpg)
