### ISSUE TITLE
Documented Parameters

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#27]
It's difficult to find out which Parameters can be used for num or bool or list. Can you specify them in the readme?

**Comment by mworion** [comment]
Hallo,

kannst Du mal reinschauen in das Realem, ob das hilft. Wenn's nicht klar ist wäre es super, wenn auch Du den Edit im Realem übernehmen könntest, so dass es die Anwender gut verstehen. Hatte ich in anderen Projekten auch so gemacht. Ich sehe sonst vor lauter Bäumen den Wald nicht mehr.

**Comment by bgewehr** [comment]
Sieht gut aus, ich mach ab sofort PRs, wenn ich was finde...

**Comment by bgewehr** [comment]
ich nehme an, Du meintest Readme? Realem klingt so lateinisch...

**Comment by mworion** [comment]
Ja klar, macht das iPhone so :-)

Von meinem iPhone gesendet
