### ISSUE TITLE
Wochenende und Wochentag für fhem

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#28]
Hallo, es hat sich bei fhem ergeben, dass man nun im Weekdaytimer sehr einfach $we für Wochenende oder Ferien oder Feiertag verwenden kann und !$we für alle anderen Tage.

fhem setzt die beiden Variablen in Abhängigkeit von gesetzten Holiday2we-Readings des global devices selbsttätig.

Das erspart so manche Logik.

Ich habe das für mich mal so eingebaut, dass ich einfach Tag 8 mit !&we und Tag 9 mit $we hinzugefügt habe und dann die Schleifen von 7 auf 9 hochgesetzt habe.

Funktionier FAST, denn in der ersten Zeile wird immer fälschlicherweise !$we UND $we auf true gesetzt, auch wenn der JSON nur einen davon hergibt.

Ich poste hier mal separat den Code. Hier schon mal das Ergebnis.
(Mach die Rolläden an Arbeitstagen um 7:00 hoch, an nicht Arbeitstagen erst um 9:30, in jedem Fall aber um 21:00 runter!)

![2015-12-01 22_37_22-start](https://cloud.githubusercontent.com/assets/4056277/11515161/b782c5b8-987c-11e5-9e28-4380e59c5e67.png)

**Comment by bgewehr** [comment]
```
var weekDays = [ 'MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU', '$we', '!$we' ];
```

```
```

**Comment by bgewehr** [comment]
Was meinst Du?
Wie kann man das mit einbringen?
Neuer Designtyp?

**Comment by mworion** [comment]
Generelle Frage: Kann man auf FHEM das so konfigurieren, dass wenn man $we nutzen will und kann im JSON dabei ist bzw. nicht dabei ist wenn nicht genutzt wird ?

Hintergrund: Es ist einfach an den übergebenen Paremetern zu erkennen, ob man eine Konfig Optionen anbieten will oder nicht. Schwierig ist, im Widget festzustellen, dass das Backend eine Option zwar hat, sie bislang aber nie gesetzt wurde. 
Ich möchte vermeiden, dass Optionen bei smarthome gezeigt werden, die dort nicht gehen bzw. umgekehrt bei FHEM. Gilt auch für die Conditions. Wenn Conditions (auch wenn nicht belegt) im JSON drin sind -> Option dafür anzeigen, ansonsten nicht. 
Gleiches für den Weekend Timer: wenn er das anbietet -> dann ist das auswählbar, wenn nicht, dann option nicht vorhanden.

**Comment by bgewehr** [comment]
Sorry für die lange Dauer bis zur Antwort!

Ich halte es für machbar, was Du beschreibst, bin aber noch nicht ganz sicher, ob ich es genau verstanden habe.

Optionsparameter für "has_weekend":true oder sowas?

**Comment by bgewehr** [comment]
By the way: frohes neues Jahr!

**Comment by mworion** [comment]
Hallo Bernd, wie kommt !we$ denn im JSON an ? an welcher Stelle ? ist es im rrule ?

**Comment by bgewehr** [comment]
Ich habe es einfach als Tag 8 und 9 definiert:
var weekdays: ['Mo','Tu','Wed','Th','Fr','Sa','Su','$we','!$we']

**Comment by mworion** [comment]
Ja hatte ich gesehen. Problem ist, dass es den RRULE string verbiegt, denn diese Einträge sind dort niocht vorgesehen. Damit muss ein neuer Design Type her.
Mein Vorschlag wäre es wie bei den Conditions zu machen und einen eintrag 'weekend' im JSON zu definieren, der dann im struct die einträge !$we:bool (wird so nicht gehen, wegen python gramaatik) und $we:bool
Ich würde dann die beiden Tasten etwas absetzen.
Wenn eintrag weekend im JSON nicht vorhanden -> keine Anzeige ganz automatisch, damit auch kein weiterer Design Type notwendig. 

Die Idee bei den ganzen Erweiterungen ist: Wenn ein Backend diese im JSON unterstützt und sendet, tauchen sie auf. Damit kann auch smarthome oder auch andere einfach aufsetzen, müssen halt nur den JSON erweitern.

**Comment by mworion** [comment]
Hallo,

ist auch umgesetzt und zwar analog der vorgehensweise bei den Conditions. die beiden felder tauchen auf, bei designType=2. Gesetzt werden die beiden durch boolsche werte im entsprechenden struct. beschreibung im header des js (holiday.weekend und holiday.work)
Ich mache keine überprüfung, ob die gesetzten werte sinn machen, ich reiche sie nur durch.
wie auch bei den conditions werden die strings automatisch erweitert, wenn nicht vorhanden. insofern sollte deine auswertelogik fürt die conditions auch dort anwendbar sein.

**Comment by bgewehr** [comment]
Es scheint noch ein Typo zu sein, der manchmal die Parameter work und weekend groß und manchmal klein schreibt. Dadurch werden bei mir beide Varianten im String ergänzt. Ansonsten leider nicht mehr optimal für Smartphone Screen, geht aber so grad noch drauf, bricht nur um.

Ich mach mich mal an die Auswertungen...

**Comment by bgewehr** [comment]
Die Reihenfolge WE und !WE erscheint im Vergleich zu MO DI MI ::: SA SO verkehrt herum. !WE und WE wäre besser. Soll ich Dir PRs machen?

**Comment by mworion** [comment]
Ja,  machen mir PRs. Wegen den Reihenfolgen und auch den Bezeichnungen in der visu einfach die Vorschläge machen, die für fhem richtig sind. Ich habe nur etwas ausgewählt.

Michel

**Comment by bgewehr** [comment]
2 PR stehen an.

**Comment by mworion** [comment]
Den PR #29 konnte ich ohne Probleme mergen,
beim PR #30 bekomme ich Konflikte aufgezeigt. Kannst Du den PR auf Basis des akzeptierten PR #29 nochmal stellen ? Die haben sie beide referenziert.

**Comment by mworion** [comment]
Liegt daran, dass Du in den gleichen Zeilen eineiigem PR die Typos korrigiert und im anderen PR die Reihenfolge geändert hast. Damit Konflikt im Berge, der nicht automatisch auflösbar ist. 
Kann aber gerne auch die Reihenfolge jetzt manuell ändern.

**Comment by bgewehr** [comment]
Komme erst heute Abend dazu!

**Comment by mworion** [comment]
Hatte Deine Korrektur Pull request direkt eingebaut. !WE kommt jetzt vor WE.
Ich machen diesen Task mal zu, bitte einen neuen fürs Bugfixing aufmachen !

**Comment by mworion** [comment]
Bernd, Sorry nochmal eine prinzipielle Frage zu den weekdays. Eigentlich sind die doch zusätzliche Bedingungen. Macht es Sinn diese nicht unter den conditions einzuordnen. Damit hätten wir auch eine reduzierte Dreite auf dem Handy. DEine Meinung dazu ?

**Comment by bgewehr** [comment]
Eigentlich ist es noch anders: wer die WE benutzt, braucht keine Mo TU WE mehr. Eigentlich nicht Condition, sondern Ersatz für die einzelnen Tage. Mir ist aber noch keine gute Idee gekommen, wie man das umschalten könnte.

Vielleicht eine checkbox vor den Wochentagen, wenn an dann nur WE sichtbar, wenn aus, dann nur Wochentage sichtbar. Spart etwas Platz, könnte grad reichen. Allerdings inkonsistent, wenn ich die Box ausmache, aber selektierte Elemente habe.

Oder doch We und !we eingereiht in die Wochentage (im fhem Weekdaytimer sind es die Tage 8 und 9), spart auch wieder ein wenn Platz. Kann ja in der rrule dennoch getrennt sein.

Oder vor den Sunrise Elementen im expert mode, da ist ja noch Platz.

Ich glaube letzteres gefällt mir am besten, das gibt eine ordentliche Aufteilung mit gut gefüllten Zeilen.

Was meinst Du?

**Comment by mworion** [comment]
Nur um es zu verstehen. Wenn WE gesetzt ist, schaut die FHEM Logik nicht mehr auf die Tage. Korrekt? Dann Knips ich die einfach in der visu aus. Kann WE$ und! WE$ Gleichzeitig wahr sein ?

**Comment by mworion** [comment]
Ich bin gerade auch am überlegen, ob es nicht möglich ist zumindest einige der FHEM Timer Funktionen mittelfristig auch ins smarthome Plugin reinzubekommen.

**Comment by bgewehr** [comment]
Es ist so, dass die Tage und WE und !we alle gleichzeitig ausgewertet werden. So ist es möglich, etwas am WE aber auch am Freitag zu schalten. WE und !we können wahr sein, weil es sinnvoll ist, den Rolladen um 9 auf jeden Fall hochgehen zu lassen, auch wenn er um 7 wegen der Ferien-Condition unten geblieben ist. Usw.

Also alles gleichzeitig möglich und auch sinnvoll.

**Comment by mworion** [comment]
Ok, dann lassen wir es erst einmal wo und wie es ist.
