### ISSUE TITLE
Neuer Typ 'txt' für flexiblere Nutzung erforderlich

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#3]
Hallo!

Für fhem benötigen wir einen zusätzlichen Typ als Ergänzung zu 'bool' und 'num'.

Ich habe mal folgendes versucht und komme schon soweit, dass das Widget richtig darstellt:
````
	switch(customFormat[0]){
		case '0':{
				template += "<tr id='uzsuNumberOfRow" + numberOfRow + "'>";
				// jetzt beginnen die spalten in der reihenfolge value, time / rrule, active, delete button
				// mit flipswitch (bessere erkennbarkeit, die Texte können über das widget gesetzt werden
				// unterscheidung nur ob bool oder num, wobei num int ist !
				if(customFormat[1]=='bool'){
					template += "<td><select name='UZSU' id='uzsuEntryValue" + numberOfRow + "' data-role='slider' data-value = '1' data-mini='true'> <option value='0'>" + customFormat[3]+ "<\/option> <option value='1'> " + customFormat[2]+ " <\/option><\/select><\/td>";
				}
				else if(customFormat[1]=='num'){
					template += "<td><input type='number' data-clear-btn='false' pattern='[0-9]*' style = 'width:40px' id='uzsuEntryValue" + numberOfRow + "'<\/td>";
				}
				else if(customFormat[1]=='txt'){
					template += "<td><select name='UZSU' id='uzsuEntryValue" + numberOfRow + "' data-role='slider' data-value = '1' data-mini='true'> <option value=" + customFormat[3]+ ">" + customFormat[3]+ "<\/option> <option value=" + customFormat[2]+ ">" + customFormat[2]+ "<\/option><\/select><\/td>";
				}
````
Ich brauche aber etwas Hilfe bei der Interpretation und dem Lese - und Schreibvorgang. Ist das für Euch auch interessant? Wäre schade, dafür forken zu müssen...

Dank Dir!

**Comment by mworion** [comment]
Hallo,
Schaue ich mir mal an. 
Michel

**Comment by mworion** [comment]
Noch eine Frage zur Klärung:
Das Ziel ist neben Bool und Num auch einen Text zu setzen, sobald die Schaltuhr auslöst? Korrekt ?

**Comment by mworion** [comment]
sorry, war zu schnell mit der Maus

**Comment by bgewehr** [comment]
Ja, die Schalter in FHEM benötigen On Off up down und solche Dinge. Dafür wäre es am einfachsten, wenn man die Beschriftungstexte für den Flip einfach als States nehmen würde, das würde den aktuellen Anspruch ausreichend bedienen.

**Comment by mworion** [comment]
Hallo Bernd
die Beschriftungstexte bekomme ich nicht einfach ein, aber Du kannst jetzt die Texte reinschreiben. Für die Smartvisu brauche ich freie Texte, da das dann z.B. eine Radiostation sein kann.
Probiere es mal aus !

-> develop v1.3beta

Michel

**Comment by bgewehr** [comment]
Ist simple, aber funktioniert, danke! Ich werde mal eine Erweiterung in Richtung select versuchen, dann haben wir mehr Freiheitsgrade.

**Comment by mworion** [comment]
Hallo Bernd,

Probiere jetzt mal die 1.5 aus, die Hat Texte als Select Element mit drin.

Michel

**Comment by bgewehr** [comment]
Auf den ersten Blick TOP! Danke Dir! Ich habe noch zwei PR gemacht wegen CSS.
