### ISSUE TITLE
DelayedExecutionCondition

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#32]
Michael, erst mal dank für die Conditions!

Wenn Du noch List hast, können wir nun das voraussichtlich letzte Thema anzugehen, die sog. DelayedExecutionCondition des Weekdaytimers in fhem.

Damit ist folgendes möglich:
"Am Montag um 22:00 schließe den Rolladen, allerdings nur dann, wenn die Terrassentür nicht geöffnet ist. Falls die Tür geöffnet ist, warte mit der Ausführung, bis sie geschlossen wird, dann schließe den Rolladen."

Oder:
"Werktags um 16:00 Uhr stelle die Heizkörper im Bad auf 21 Grad, allerdings nur dann, wenn wir zuhause sind (Condition) und wenn das Badezimmerfenster nicht geöffnet ist. Wenn das Fenster geöffnet ist, warte bis es geschlossen wurde, dann stelle die Temperatur ein. (DelayedExecutionCondition)"

Technisch ist das eine zweite Condition derselben Art wie die erste, aber mit der Bezeichnung DelayedExecutionCondition. Sonst alles wie gehabt.

Details: 
http://fhem.de/commandref.html#WeekdayTimer

Hast Du noch Lust oder machen wir erst mal eine Pause?

**Comment by mworion** [comment]
Hallo Bernd,

können das fertigmachen, sofern der erst schon läuft. Nur für mich zum verstehen: Im Grunde geht es darum eine weitere Zeile reinzubringen, wo eine andere Art von Conditions eingegeben werden kann ?
Langsam wird das aber richtig voll!

**Comment by mworion** [comment]
Habe mir das in der FHEM Spek angesehen. Könnte auch mit einem weiteren Feld bei der Conditions Zeile gehen. Was ich brauche ist die Liste der Parameter, die Du eingeben / verändern willst.

**Comment by bgewehr** [comment]
Es handelt sich bei der DelayedExecutionCondition um dieselbe Machart wie die Condition. Vergleich Device Value oder Perl String. Also "einfach" das Gleiche noch einmal. 

Btw: Ich habe heute erfolgreich das Anheben der Schlafzimmer Rolläden durch eine Condition (NRW_Ferientag ne "1") verhindert. Ein Traum...

**Comment by mworion** [comment]
Hallo Bernd,

probier die v4.4 aus, sollte alles drin sein. 

Aber Achtung !!!!! : 

Ich musste der Ordnung wegen die key/value pairs im JSON nochmal ändern. Da ich die FHEM Zeilen jetzt doppelt habe, ist die Beschreibung 'condition' aus dem key bei 'conditionType', usw. herausgefallen. Es ist jetzt nur nor 'type'. Die Zuordnung wird ja schon im übergeordneten Struct getroffen. Die Beschrebung war ja doppelt drin und die Zeilen sind kaum noch lesbar gewesen. Bitte korrigiere das in Deiner Auswertung. Danke Dir !

Frohe Ostern wennes so passen würde !

Michel

**Comment by bgewehr** [comment]
Das Osterfest ist gerettet! Dank Dir! Ich berichte dann!

**Comment by mworion** [comment]
Da freue ich mich ja 😀.
Gestaltungs und Textwünsche natürlich offen.

**Comment by mworion** [comment]
Bernd,

bei mir aktuell die v4.5. Funktional nichts geändert. Sie etwas besser aus, habe den Design Type = 1 entfallen lassen, weil ohnehin keine Nutzer da. FHEM bleibt aber weiterhin designType = 2

**Comment by bgewehr** [comment]
Großartig! Die fhem community arbeitet schon am neuen uzsu_execute... Tolle Sache! Ich schau es mir an.

**Comment by bgewehr** [comment]
4.5 gefällt mir sehr gut! Due vertikalen Texte passen super und erklären alles.

Btw: Hast Du den act button für sunrise noch auf dem Schirm?

**Comment by mworion** [comment]
Ja, habe ich. Muss mir aber noch Gedanken machen, dass in die gleiche Logik umsetze.

**Comment by mworion** [comment]
Hallo Bernd,

Sunrise und Sunset ist umgestellt.
Die Formatrierung (Act Button rechtsbündig will ich noch machen)
Ich habe noch einen Darstellungsfehler beim Erstellen einer Zeile

Wichtig: Ich habe nochmals den JSON anpassen müssen: Nur eine Bezeichnungsänderung. Ich habe dort wo 'Perl' steht das gegen 'String' geändert. Warum: Wenn ich die Funktionen in smarthome nachbaue, dann kann keiner etwas mit 'Perl' anfangen, weil dort alles in Python ist. Ist im Header auch beschrieben. Sorry dafür, muss ich aber vor dem Release machen. Später will dort keine mehr anpacken.

**Comment by mworion** [comment]
Ach ja: ist die V4.6

**Comment by bgewehr** [comment]
Super! Kein Ding, das ist schnell umgebaut.
Ich bin wegen Smartphone Display immer noch auf der Such nach Platz für die WE Buttons. Neben Sunrise wäre dich auch jetzt noch noch Platz im Displaytype 2?

**Comment by mworion** [comment]
Hallo Bernd,

mein Fehler habe ich gefunden und gefixed.
Die WE udn !WE habe ich in die zeile  SUN reingepackt
Alle Felder, die nicht mit Act aktiuviert wurden, können nicht mehr beschrieben werden.

Gib mal Feedback, was Du davon hälst

**Comment by mworion** [comment]
So mit der v4.8 sollte mal alles (bis auf die JSON umstellung alles mal da sein. jetzt ist noch Fehlersuche angesagt. Komme aber heute nicht mehr weiter.

**Comment by mworion** [comment]
Wie sieht es mit diesem Feature im Test aus ?

**Comment by bgewehr** [comment]
Für mich ist das hier erfolgreich abgeschlossen!
