### ISSUE TITLE
In V4.6 dev gehen die "normalen" Uhrzeiten verloren

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#34]
Fehleranalyse folgt...

Stell irgendeine Uhrzeit bei "time" ein, dann OK, dann wieder aufrufen, Uhrzeit = 00:00.

**Comment by bgewehr** [comment]
![2016-03-28 19_59_07-starten](https://cloud.githubusercontent.com/assets/4056277/14085342/9430ea0e-f51f-11e5-87a3-b2029efb7e2a.png)
Muss beim setzen aus dem JSON passieren, der Output erscheint mir korrekt zu sein:
`{"active":true,"list":[{"timeMax":"","holiday":{"weekend":true,"work":true},"delayedExec":{"type":"String","deviceString":"device2","value":"3","active":true},"time":"01:01","rrule":"FREQ=WEEKLY;BYDAY=WE,TH","condition":{"value":"2","active":true,"type":"String","deviceString":"device1"},"timeOffset":"","active":true,"value":"1","timeMin":"","event":"time","timeCron":"01:01"}]}`

**Comment by mworion** [comment]
Ja, ist mir klar wo das passiert. Setze ich explizit. Hatte ich auch bei Sunrise / Suset durch SUN ersetzt. Dort habe ich es aber wieder zurückgebaut, das es wieder auftaucht. Sollte kein Problem sein.

**Comment by bgewehr** [comment]
Kannst Du in dem Zusammenhang mal erklären, was timeCron und was time ist? Wozu braucht man zwei Uhrzeiten, die immer gleich sind?

**Comment by mworion** [comment]
Hallo Bernd,
in v4.7 jetzt wieder OK.
Der Zusammenhang ist die Altlast von smarthome. Dort ist alles in einem String eingebaut Time und SUN. Das muß ich immer wieder auseinandernehmen und zusammenbauen. Daher zwei Zeiten.
Ich werde jetzt Mal in der smarthome Community versuchen, das UZSU Plugin anzupassen, um auch hier im JSON wieder klarheit zu schaffen. Ich würde das gerne gleich wie die Conditions und DelayedExecs im Json einbauen.
Am liebsten schon vor dem Release im Zusammenhang mit FHEM für Euch. Damit braucht ihr dann hinterher nicht mehr zu ändern. Ich würde in zwischenzeit mit der v4.8 auf develop beide JSON Einträge unterstützen.

**Comment by mworion** [comment]
...ich mache mal einen Vorschlag dazu

**Comment by mworion** [comment]
Hier mal das neue Modell.
sun analog zu den anderen Themen
später entfallen dann timeMin, timeMax, timeOffset, event im Original Json

// Datenmodell: Austausch über JSON Element
//              {   "active"    : bool, 
//                  "list"      :                   Liste von einträgen mit schaltzeiten
//                  [   "active"    :false,         Ist der einzelne Eintrag darin aktiv ?
//                      "rrule"     :'',            Wochen / Tag Programmstring
//                      "time"      :'00:00',       Uhrzeitstring des Schaltpunktes / configuration
//                      "value"     :0,             Wert, der gesetzt wird
//                      "event":    'time',         Erweiterung zur Laufzeit: Zeitevent oder SUN
//                      "timeMin"   :'',            Untere Schranke SUN
//                      "timeMax"   :'',            Oberere Schranke SUN
//                      "timeCron"  :'00:00',       Schaltzeitpunkt
//                      "timeOffset":''             Offset für Schaltzeitpunkt
//                      "sun" :         {   timeMin :   text    Untere Schranke SUN
//                                          timeMax :   text    Oberere Schranke SUN
//                                          timeOffset: text    Offset für Schaltzeitpunkt
//                                          event :     text    Event (ist sunrise oder sunset)
//                                          active :    bool    Aktiviert ja/nein
//                                      }
//                      "condition" :   {   Ein Struct für die Verwendung mit conditions (aktuell nur FHEM), weil dort einige Option mehr angeboten werden
//                                          "deviceString"  : text  Bezeichnung des Devices oder Auswertestring
//                                          "type"          : text  Auswertetype (logische Verknüpfung oder Auswahl String)
//                                          "value"         : text  Vergleichwert
//                                          "active"        : bool  Aktiviert ja/nein
//                                      }
//                      "delayedExec":  {   Ein Struct für die Verwendung mit delayed exec (aktuell nur FHEM), weil dort einige Option mehr angeboten werden
//                                          "deviceString"  : text  Bezeichnung des Devices oder Auswertestring
//                                          "type"          : text  Auswertetype (logische Verknüpfung oder Auswahl String)
//                                          "value"         : text  Vergleichwert
//                                          "active"        : bool  Aktiviert ja/nein
//                                      }
//                      "holiday":      {
//                                          "work"      : bool  Aktiviert ja/nein
//                                          "weekend"   : bool  Aktiviert ja/nein
//                                      }
//                  ] 
//              }

**Comment by bgewehr** [comment]
Ah, so.
Mir gefällt die Redundanz des events noch nicht.
Ein event reicht doch in der ersten struct Ebene, das dann time, sunrise oder sundown aufnehmen kann.
Work oder workday? Native speaker vor...

**Comment by mworion** [comment]
Ja, event würde / müßte aus der ersten Ebene herausgenommen werden. Ich könnte es auch in der ersten Ebene lassen, er gehört aber nur zum Sunset Sunrise und sonst nichts. Im Plugin, das ich mir angeschaut habe passiern auch Klimmzüge, um das auseinander zu nehmen und zusammenzubauen. Das würde mit einer Überarbeitung komplett entfallen.

Ich könnte auch event "type" nenen, wie auch bei den anderen Strukturen.

... oder ich verstehe nicht, was Du meinst...

**Comment by mworion** [comment]
wenn Du nach work oder workday fragst, dann eher workday (zumindest nach leo.org)

**Comment by mworion** [comment]
Ganz andere Frage:

Ist mir gerade gekommen: Wertet Ihr in FHEM den JSON aus oder parst ihr den time eintrag wie bei smarthome ?
Wenn ich mich recht entsinne, dann nutzt Ihr schon dir JSON elemente. smarthome noch nicht, daher könnte ich das jetzt umstellen.

**Comment by bgewehr** [comment]
Eigentlich finde ich Event auf der ersten Eben am besten und Time, Sunrise und sundown sind die Events, die den trigger auslösen. Lässt sich leicht mit if then Else abfragen.
Wenn Dir aber die andere Lösung deutlich besser erscheint: Type in Sun finde ich dann auch gut. Dann muss man aber drumherum fragen wenn nicht Sun, dann ist es wohl Time. Geschmacksache, denke ich.

Wir machen nur JSON in fhem. Was anderes kommt gar nicht bei uns an.
V
Also workday. Gut.

**Comment by mworion** [comment]
Vom Prinzip stimme ich dir zu, würde aber sofort mit smarthome brechen, da Time der Zentrale Austausch Punkt ist. Da habe ich keine Idee der Migration.

**Comment by bgewehr** [comment]
Ich weiß nicht, ob wir an einem Punkt aneinander vorbei reden: ich meine Event sollte so bleiben wie jetzt. Das geht doch offenbar in beiden Welten jetzt auch.

Mögliche Werte: "time", "sunrise", "sundown"

Der SUN UI Bereich enthält dann eben das Auswahlelement dafür, der SUN Struct aber nicht den key:value.

Meinen wir das gleiche?

**Comment by mworion** [comment]
Da haben wir aneinander vorbeigeredet. Event wird in smarthome gar nicht verwendet, es ist nur der Key Time in Gebrauch. Aus den Values dieses Keys entstehen dann Event usw. Und auch die zweite Zeit (die dann nur Zeit ist und nicht mehr alles mögliche). Aus dieser Zwickmühle will ich raus, wenn es sinnvoll geht, weil ich immer die Key:Value werte erstellen bzw. parsen muss. Das gleiche passiert auch auf dem smarthome Plugin. Macht so keinen Sinn.
Aber das wäre ein grundsätzlicher Schritt. Muss nochmal etwas mehr nachdenken.
Aktuell muss das alte ja noch gehen.

**Comment by mworion** [comment]
Nachdem ich jetzt nochmal darüber geschlafen habe: wenn wir den Key "event" als Kernelement verwenden wollen und dort die Zustände "Time", "Sunrise", "Sunset"  nutzen wollen, dann macht das Tag "ACT" für die "SUN" Zeile keinen Sinn. Diese Funktion wird ja über das Pull-Down Menü übernommen (wie es in Vergangenheit war). Geht aus meiner Sicht auch und wäre auch stimmig. 

Würde dann aussehen:

"event" : { "type"              : text; time,sunset,sunrise
                 "timeMin"        : text; Untere Schranke SUN
                 "time"              : text; Schaltzeitpunkt
                 "timeMax"       : text; Obere Schranke SUN
                 "timeOffset"    : text; Offset für Schaltzeitpunkt in Minuten
              }

oder wir lassen alles flach, wie es aktuell ist (Wäre jetzt ,meine Tendenz).

**Comment by bgewehr** [comment]
Aus rein hygienischen Aspekten finde ich den Event Struct sauber. Nötig ist er nicht, denke ich, da die oberste JSON Struct Ebene dies ebenfalls ausreichend kapselt.

Der Punkt ist doch, dass man in der obersten UI Zeile nicht genug Platz hat, um die Event Auswahl dort zu platzieren. Deswegen machen wir ja den Umweg über einen Act und einen Select Button, Act=false bedeutet Event = TIME, Act = true bedeutet Event = Select. Solange wir keinen Event-Select mit Time Sunrise sundown in der ersten Zeile der UI platziert bekommen, finde ich die Act + Select Lösung sauber und intuitiv benutzbar.

Ok für Dich?

**Comment by mworion** [comment]
OK, dann lassen wir das so, wie es in der v4.8 umgesetzt ist. Die Logikweiche "Event = TIME, Act = true bedeutet Event = Select" muss ich dann in der Visu für die UI behalten, sobald es ein Design gäbe (eher unrealistisch), dass den Pulldown in der ersten Zeile darstellt, kann ich die UI noch umbauen.

**Comment by bgewehr** [comment]
Sehe ich auch so.

**Comment by bgewehr** [comment]
Einzige Chance wäre, in die Höhe zu bauen und die Wochentage in zwei Zeilen anzuordnen, aber das wird ein Gefummel bei ungerader Anzahl... Lassen wir lieber.

**Comment by mworion** [comment]
OK, dann bitte Testen, ob die Funktionen so OK. Ich habe die Checks herausgenommen und versuche gerade die Umsetzung time -> expand herauszulassen. Sollte funktionieren.
