### ISSUE TITLE
Vorschlag für compact layout

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#35]
![2016-03-28 20_09_19-starten](https://cloud.githubusercontent.com/assets/4056277/14085742/e5a174e2-f521-11e5-8f55-d3af2115a717.png)

**Comment by bgewehr** [comment]
Deine Lösung ist besser. Wenn Holiday nach SUN kommt, dann ist Act auch ganz klar für sun reserviert.

Eine gestrichelte Trennlinie wäre ganz nett...
![2016-03-28 20_24_50-starten](https://cloud.githubusercontent.com/assets/4056277/14085977/29b983da-f523-11e5-8b64-7489ff9d6b59.png)

**Comment by bgewehr** [comment]
![2016-03-28 20_24_51-starten](https://cloud.githubusercontent.com/assets/4056277/14086057/892575cc-f523-11e5-96b1-576012db0fb5.png)

**Comment by bgewehr** [comment]
evtl. würde der Del button mit einer Mülltonne (ui-icon-trash ) etwas kleiner...

**Comment by bgewehr** [comment]
Weitere Gedanken:
Unten könnte - nur der Ordnung halber - der Active Checkbox auch durch den Act-toggle ersetzt werden, der oben immer verwendet wird. Einheitlich.
Versionsnummer inline mit action buttons? spart eine ganze Zeile...
Actions rechtsbündig? Ist so üblich bei Dialogen...

**Comment by bgewehr** [comment]
![2016-03-28 20_24_52-starten](https://cloud.githubusercontent.com/assets/4056277/14086868/9c126b5a-f527-11e5-9d1b-b1088ca6fc65.png)

**Comment by bgewehr** [comment]
![2016-03-28 20_24_53-starten](https://cloud.githubusercontent.com/assets/4056277/14086983/25866e5e-f528-11e5-9524-b0d413355a1c.png)

**Comment by bgewehr** [comment]
alles nur Vorschläge...

**Comment by mworion** [comment]
das mit der gestrichelten Linie fände ich auch gut. Ich bekommen nur die beiden Zeilen noch nicht in eine Zeile. Da hört erst einmal mein CSS Wissen auf...
...damit muss ich erst mal etwas weiter lernen...

**Comment by mworion** [comment]
Ist so gemacht, habs gelernt. Finde ich gut so. Sollten wir setzen lassen.

**Comment by bgewehr** [comment]
![image](https://cloud.githubusercontent.com/assets/4056277/14089519/9009ab62-f535-11e5-8e5f-b3646bd05330.png)
Sieht gut aus.

**Comment by bgewehr** [comment]
Die Deaktivierung der Elemente ist OK, aber die oberste Zeile verhält sich anders, dort bleibt alles aktiv, auch bei inact.
![image](https://cloud.githubusercontent.com/assets/4056277/14089575/d71d5576-f535-11e5-80b8-214a5067ab68.png)

Nicht schlimm, nur ein Hinweis.

**Comment by mworion** [comment]
Stimmt. Brauchen wir das disablen bei deaktivierter ACT eigentlich? Machen kann man es ja, ist halt viel Code drumherum, kann auch entschlacken.
Im Moment tendiere ich sogar es wieder herauszunehmen.

**Comment by bgewehr** [comment]
Ich persönlich brauch es nicht, arbeite sogar lieber andersherum: erst alles einstellen, dann aktivieren.

**Comment by bgewehr** [comment]
Es ist möglicherweise besser mit disable, weil dann das Verhalten durch die Darstellung besser repräsentiert wird.

Wird aber stressig, das komplett durchzuhalten:
Wenn die ganze UZSU deaktiviert wird, dann müsste ja alles disabled sein, auch die Act Buttons.

Wäre aber konsequent und für Gelegenheitsnutzer besser verständlich.

Ich finde: alles oder nichts, wenn alles zu viel wird, dann lieber nichts.

**Comment by bgewehr** [comment]
Schaust Du in meinen obigen Vorschlägen noch mal nach unten? Ich hatte mal überlegt, die Buttonleiste nach unten rechts zu verschieben, weil das i. A. so üblich ist. Was hältst Du davon?

**Comment by mworion** [comment]
Mach ich, kein Problem

**Comment by mworion** [comment]
Also, wenn ich mir das im Hochformat auf Handys anschaue, wo der Rest linksbündig ist, dann sieht das etwas komisch aus:

![ohne titel](https://cloud.githubusercontent.com/assets/6632980/14395485/57fcc060-fdd2-11e5-821e-c08a7f25d182.png)

Aus wenn ich die Versionsnummer inline mache, verliere ich Breite. Irgendwie müssen wir wohl einen Tod sterben. Im Breitformat ist Dein Vorschlag etwas schöner.
Wegen dem Button: Ja Stimmigkeit mit gleichartigem Act ist zwar Richtig, aber die Unterscheidung in Richtung das gilt jetzt für die Gesamte Schaltuhr hilft sehr, sonst müßte ich das etwas (wieder mit gestrichelter Linie) abtrennen.

Aus meiner Sicht entweder so lassen wie es war, oder auf Breitformat setzen (nutze ich ausschliesslich), Block rechtsbündig und die Versionsnummer links inline.

Ich bin das leidenschaftslos, Deine Entscheidung !
