### ISSUE TITLE
Responsive 4.8 Färbung des expert Buttons

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#37]
Der expert Button färbt sich, wenn im expert Bereich Werte gesetzt sind, sonst bleibt er schwarz.

Seit die Holiday im expert Bereich liegt, müsste auch ein gesetzter Holiday Wert den Button einfärben, richtig?
![](http://i.imgur.com/QEq9AB3.jpg)

**Comment by mworion** [comment]
Ja sollte er und hatte auch mal bei mir funktioniert. Dem gehe ich mal nach.

**Comment by mworion** [comment]
Probiere mal die 4.81. Da habe ich das nicht feststellen können.

**Comment by mworion** [comment]
Hallo Bernd, aktuell steht bei mir die Entwicklung auf der Widget Seite, bin jetzt eher im Plugin (für Euch weniger interessant).
Aktuelle Erkenntnisse, was noch an Fehlern vorhanden ist oder seid Ihr schon glücklich ?

PS: eine Frage Off Topic: Wie werden die Variablen WE und !WE bei FHEM berechnet / ermittelt kannst Du mir da einen Hinweis / Link geben ?

**Comment by bgewehr** [comment]
Es gibt in fhem ein Objekt global, das allgemeine Settings speichert. Dort gibt man im Attribut holiday2we den Namen des devices an, das die Feiertage liefert. Es ist ein Device vom Typ Holiday und liefert für gestern, heute und morgen entweder none oder den Namen des Feiertages.

http://fhem.de/commandref#global

Die Feiertage sind nicht nur pro Region, sondern auch individuell unterschiedlich. Der eine hat an Rosenmontag frei, der andere nicht.

Daher ist das Holiday Modul in fhem kein iCal abo sondern wird durch ein lokales Textfile gesteuert.

http://fhem.de/commandref#holiday

Die bisherigen Tests haben keine neuen Erkenntnisse mehr gebracht. Bis auf responsive error bei pivot und der Farbe des expert Buttons habe ich bisher nichts gefunden. ;-))

**Comment by mworion** [comment]
OK, aus meiner Sicht sollte ab der v4.81 der Expert Button richtig gefärbt sein (auch bei WE). Sofern weiterhin Problem, müssen wir suchen.

**Comment by mworion** [comment]
Wie schaut's aus? Färbung mit der 4.81 OK ?

Ich laufe gerade auf das Release zu v5.0 aktuell mache ich die v4.9, dorthabe ich einige kleine Änderungen für iOS9 eingebracht (ob die was helfen, weiss ich nicht)

**Comment by bgewehr** [comment]
Nein, leider nicht. Bleibt bei 4.81 wie oben abgebildet.

**Comment by mworion** [comment]
Hallo Bernd,
ich kann es bei mir mit den v 4.9 (aber auch schon v 4.82 bzw. v4.81) nicht nachvollziehen. Bei mir klappts perfekt. Ist stelle die Färbung mit
        $('#uzsuExpert' + numberOfRow).closest('div').addClass('ui-checkbox-on');
bzw. remove class um. 
Kannst Du mir etwas näheres über Dein Setup sagen ? Wichtig auch, dass die widget_uzsu.html mit aktualisiert wird, weil ich ursprünglich dort über css gesteuert hatte und nachdem Du das mit der Farbe rot angemerkt hattest es auf die aktive Farbe des Themes umgestellt hatte.
Aktuell komme ich bei der Fehlersuche nicht weiter.

**Comment by bgewehr** [comment]
Mene Screen Shots kommen vom iPhone, hatte ich das erwähnt?

**Comment by mworion** [comment]
Nein,
aber ich habe es gerade mit einem iPhone 6 ausprobiert iOS 9.3.1 kein Problem mit der Färbung des Expert buttons. Auch in der Simulation auf dem Safari auf dem Mac kein Problem. Immer dann, wenn ich einen Item auf ACT haben, ist der Expert Button grün.

**Comment by bgewehr** [comment]
Ja das ist bei mir auch so. Allerdings wird nicht gefärbt, wenn nur WE benutzt wird. Darum geht es mir.

**Comment by mworion** [comment]
Ja soweit klar soll so sein. Ist bei mir aber auch so !?
![img_2777](https://cloud.githubusercontent.com/assets/6632980/14502043/a2d682ee-01a9-11e6-9d0c-5e46156a6bca.PNG)

**Comment by bgewehr** [comment]
Ich prüfe noch mal am PC.

**Comment by mworion** [comment]
Wäre super, bin im Moment etwas hilflos, was die Fehlersuche angeht.

**Comment by bgewehr** [comment]
Also meine Beobachtung ist folgende:
Das Färben klappt während der Dialog geöffnet ist einwandfrei.
Sobald ich schließe und neu öffne, ist die Farbe wieder weg.
Also ein initial refresh Problem?

**Comment by mworion** [comment]
Danke, das war der Hinweis. Ich hatte die Auswertung der Button Farbe vor dem Setzen der Werte. V4.91 sollte es richten.

**Comment by bgewehr** [comment]
Fixed
