### ISSUE TITLE
Cancel schließt das Popup nicht und (x) speichert die Änderungen

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#5]
Es gibt drei verschiedene Arten, das Popup zu schließen:
1) per save&quit
2) per Cancel
3) per (X) oben rechts

1) ist OK, allerdings ist mir aufgefallen, dass der Klick nicht verzehrt wird und auf darunter liegende Elemente erneut wirksam wird. Keine Ahnung, warum.

2) macht bei mir gar nichts

3) müsste sein wie Cancel (Abbrechen ohne Änderung speichern), wirkt aber wie save&quit (mit Änderung speichern)

Aktuell kommt man nicht ohne speichern wieder raus, auch wenn man Mist gemacht hat...

Siehst Du ne Chance, das zu verbessern? Ich habe leider keine Ahnung, wo genau das passiert.

**Comment by mworion** [comment]
Hallo Bernd,

kurze Anmerkung: auch bei Cancel wurden die Werte nicht gespeichert, blieben aber in der Darstellung.

mit der v1.4 arbeiten Punkte 1-3 so wie erwartet.

Michel
