### ISSUE TITLE
Zeit relativ zu sunrise und sunset möglich?

### ISSUE THREAD

**Issue by bgewehr** [mworion/uzsu_widget#6]
Viele haben nach der Möglichkeit gefragt, die Zeit relativ zum Sonnenaufgang oder -untergang zu formulieren.

Ich könnte mir vorstellen, ein select vor time zu erstellen, das --, SA, SU enthält. Das wäre dann so zu verstehen:

SA 01:00 ist eine Stunde nach Sonnenaufgang
SU 00:30 ist eine Stunde nach Sonnenuntergang
 --   21:00 ist um 21:00 Uhr

Relativ VOR SA und SU ist ohne negative Zeiten aber nicht möglich.

Könnte man wiederum mit --, SA+, SA- SU+, SU- adressieren.

Hast Du dazu schon was im Kopf?

**Comment by bgewehr** [comment]
Sowas wie:

````
				//sunrise und sundown selector
				template += "<td><select ' name='uzsuSUN" + numberOfRow +"' id='uzsuSUN" + numberOfRow +"' data-mini='true'><option value='-'>--</option><option value='SA+'>SA+</option><option value='SA-'>SA-</option><option value='SU+'>SU+</option><option value='SU-'>SU-</option></select><\/td>";
````

Zwischen value und time, sieht gar nicht schlecht aus!

**Comment by mworion** [comment]
Hallo Bernd

hatte ich schon in den Pull request geschrieben. Es gibt bei smarthome.py im UZSU Plugin die Möglichkeit <sunset+1 anzugeben. Das schreibst Du einfach in den Zeitstring rein. Damit ist die Funktion hier schon gegeben. Ein Aufbohren des Dicts geht nicht wirklich, da das dicts und die Schnittstelle zum Widget durch das Plugin vorgegeben ist. Das kann ich nicht ändern.

Kannst Du nicht versuchen, das auch so nach FHEM so reinzubekommen ?

Michel

**Comment by bgewehr** [comment]
Im Fhem kann man schreiben {sunrise(1800)}, das heißt dann 30 Minuten nach dem Sonnenaufgang.

Ich fand das nur nicht schön für die Benutzer!

Kann ich aber zur Not auch erst mal mit leben. PR zurückgezogen!

**Comment by bgewehr** [comment]
Man könnte allerdings auch den String jeweils so zusammensetzen, wie man ihn braucht, für SH oder fhem, aber dennoch auf der Oberfläche die Steuerelemente fprndie User anbieten, um es auch elegant eingeben zu können. Wir kriegen doch im JavaScript auch hin, einen Zeitstring daraus so oder so zu gestalten und beim Lesen Rückwärts, oder?

**Comment by mworion** [comment]
Das nehme ich nochmal mit, ob so etwas sinnvoll möglich ist. Hast Du eine Idee, wie man sh und FHEM unterscheiden kann (evt. etwas eleganter als nur einen Parameter mit dazuzugeben)

**Comment by bgewehr** [comment]
Es geht eigentlich auch so, dass in fhem die Übersetzung von <Sunset+2 in {sunset(7200)} erfolgt, ist dort nun nicht unmöglich. Besser eine gemeinsame UZSU und Interpreter im fhem Modul.

**Comment by bgewehr** [comment]
Ist dies hier für Dich verworfen oder verschoben?

**Comment by mworion** [comment]
Im Moment verschoben. Ich hab im Moment noch andere Sachen zu tun, und da hat das Prio 2, wird also eher etwas brauchen.

**Comment by mworion** [comment]
Hallo Bernd,

ich hab gerade angefangen mir einmal Gedanken dazu zu machen. In smarthome gibt es das Format
[H:M<](sunrise/sunset)[+/-][offset][<H:M]. Könnt Ihr das bei FHEM in gleicher Weise nutzen ? Neben offset gibt es nämlich auch die Möglichkeit Lower und Upper Boundaries zu setzen.

Michel

**Comment by bgewehr** [comment]
Kannst Du mal ein oder zwei Beispiele angeben, damit ich es noch besser verstehen kann?

**Comment by mworion** [comment]
17:30<sunset<19:30 heißt: trigger zu sunset, aber nicht früher wie 17:30 und spätestens um 19:30

**Comment by bgewehr** [comment]
In fhem haben wir auch upper und lower boundaries:
http://fhem.de/commandref.html#SUNRISE_EL

Das geht dann so: {sunset(<type>,<offset in sec>,<min>,<max>)}

type ist ein bisschen speziell, sowas wie Normal Null -> ;-) Kann  "REAL", "CIVIL", "NAUTIC", "ASTRONOMIC" sein.

**Comment by mworion** [comment]
OK, dann macht es auch für Euch sinn, diese Parameter mit über das Widget abzubilden. Ihr könnt die dann auch nutzen.

**Comment by bgewehr** [comment]
klingt gut!

**Comment by mworion** [comment]
Dann muß ich mal nachdenken, wie das am besten in die Architektur passt.

**Comment by mworion** [comment]
Noch eine Frage: kommt das häufig vor oder ist das eher eine Ausnahme es so genau zu nutzen ?

**Comment by bgewehr** [comment]
Wer kann das sagen? Mein Ziel ist es, die Freiheitsgrade in fhem über ein elegantes Frontend in SV den Nutzern einfach benutzbar wieder anzubieten. (-> eher Ausnahme als Regel, aber für die, die die Ausnahme wollen, eher Pflicht als Kür!) Mir liegen Nachfragen vor, wie man das dann, wenn die Zeit stimmt, mit Regeln versehen kann
- außer wenn Ferien sind
- außer wenn Feietrag ist
- außer wenn noch jemand zuhause ist

usw. Fhem hat dafür eine Bedingung, die man entsprechend setzen kann:

http://fhem.de/commandref.html#WeekdayTimer (siehe Condition!)

**Comment by mworion** [comment]
Das mit den Regeln ist dort möglich, wo ich das in der rrule abbilden kann. Abhängigkeiten in Bezug auf Systemzustände gibt es auf smarthome Seite nur in der Logik. 
Mein Idee ist, neben den Standard Einträgen (wie gehabt, Ist-Zustand) einen geführten Assistenten zu bauen, der das Ergebnis einträgt.

**Comment by bgewehr** [comment]
Ist das dann doch Popup im Popup?

**Comment by mworion** [comment]
Nein, das geht ja nicht. Ich jetzt viel gewälzt, aber nur harte Aussagen von den Entwicklern des Frameworks gehört. Aber ich habe da ein paar Ideen dazu....

**Comment by bgewehr** [comment]
OK, ich bleibe neugierig!

**Comment by mworion** [comment]
Hallo Bernd,

ich hatte es befürchtet: es ist eine riesen Orgie wegen dem parsen der Daten im Widget. 

Dennoch: Ich habe einmal einen Branch "feature" mit der v1.87 angelegt. 
Ich habe mal keine Beschriebung dabei, probiere und teste mal möglichst genau aus. 
Feedback welcome. Am geschicktesten startest Du das Widget mit designType = '1', damit Du auch die Zeile selbst editieren kannst.
Die Wochentage sind nicht funktional.

Michel

**Comment by bgewehr** [comment]
Ok, ich schau es mi an!

**Comment by mworion** [comment]
Habe noch etwas aufgeräumt. Ist jetzt v2.1 im feature branch

**Comment by bgewehr** [comment]
OK, ich sehe jetzt im designtype 1 zwei Texteingabefelder. Was genau sollte ich testen? Sorry, ich blicke es noch nicht so ganz!

**Comment by bgewehr** [comment]
Habe eben den Helper entdeckt! Hatte irgendwie 2.0RC1 geladen anstatt R2.1 Test jetzt!

**Comment by mworion** [comment]
Sorry

**Comment by bgewehr** [comment]
Hab heute zuwenig Zeit. Irgendwie bin ich noch verwirrt, der zweite Eintrag hat ein merkwürdige Reihenfolge:

    {"active":true,"list":[{"value":"On","time":"09:00<sunrise<21:00","rrule":"FREQ=WEEKLY;;BYDAY=MO,TU,WE,TH,FR,SA","active":true},{"rrule":"FREQ=WEEKLY;;BYDAY=MO,TU,WE,TH,FR,SA","time":"21:00","value":"Off","active":true}]}

**Comment by bgewehr** [comment]
Erste Tests ergeben noch einige Unstimmigleiten:
In UZSU-Dialog:
Neue UZSU, neue Zeile -> (?) ohne Funktion
Neue UZSU, neue Zeile, manuelle Zeit und Tage, speichern -> (?) geht!

Auf mobile ist keine Screen-Rotation mehr möglich, weil das Format sich nicht mehr anpasst!

Im Assistenten:
Wenn der input nur eine Zeit ist und man umschaltet auf Sunrise, dann passieren mehrere Dinge:
1. Fehlermeldung in der Console: 
The specified value 'sunrise' does not conform to the required format.  The format is 'HH:mm', 'HH:mm:ss' or 'HH:mm:ss.SSS' where HH is 00-23, mm is 00-59, ss is 00-59, and SSS is 000-999.

2. Die vorherige Zeit ist weg, wenn man wieder auf 'normal' umschaltet

Nach einigem Klicken völlig zerstörte Struktur der Daten:
![uzsustrukturkaputt](https://cloud.githubusercontent.com/assets/4056277/6655866/059182f0-cb12-11e4-8a1b-4a4031a7bdeb.png)

Ich komme im Moment nur zur Symptomanalyse und kann Dir noch keine Code-Hinweise geben, mache ich aber gern später!

Insgesamt ist es sehr schwierig, sich ein umfassendes Layoutkonzept vorzustellen, das über alle diese Möglichkeiten verfügt, ohne den Benutzer völlig zu überfordern. Wir haben ja noch einige Dinge übrig bei den Wochentagen: "Auch an Feiertagen (ja/nein)", "Auch an Ferientagen(ja/nein), Zufallsschaltungen zwischen zwei Zeitpunkten, ...

Wie wäre es, wenn man die Navigation nicht durch den Wechsel zwischen mehreren Popups erledigt, sondern durch das Erweitern von Abschnitten? Standardanzeige ist dann die normale UZSU, aber wenn ich (V) drücke, erweitert sich der Abschnitt und die Profi-Funktionen kommen zum Vorschein, das fände ich etwas einfacher zu verstehen als das Springen zwischen Popups. Was meinst Du?

**Comment by bgewehr** [comment]
So etwa, was meinst Du?
![uzsuexpandable](https://cloud.githubusercontent.com/assets/4056277/6655951/53542cf0-cb16-11e4-8330-91ff24736f15.png)

**Comment by bgewehr** [comment]
Ereignis könnte dann auch noch "Zufall" sein...

**Comment by bgewehr** [comment]
Vielleicht sollten wir auch mal fragen, für welchen Markt wir das Ganze entwickeln. Wenn international, dann weiter mit englisch, wenn nicht, dann lieber alles auf deutsch?

**Comment by mworion** [comment]
Hallo Bernd,

danke für das Feedback. Mal meine Pukte dazu:
#28: muß ich mir ansehen, was geändert wurde. Eigentlich passiert das abspeichern immer noch so wie vorher.
#29: Keine Funktion: hatte ich auch gesehen, fehlte ein callback. 
		Zu den Drehungen: ist immer dei Balance alles auf einem Popup, aber dennoch klein.
		Zu den Fehlermeldungen: auch hier abgleich in einem Feld Zeit (kann als Input = 'time')  deklariert werden, wenn dann sunrise drinsteht geht es nicht. in der UZSU ist das ein einziges Feld.
		   Wenn Du dazu eine Idee hast -> welcome.
		Die Komplexität hatte ich auch so erlebt. Du bestätigst das.
#30: Der Vorschlag schaut gut aus. Kann ich mir gut vorstellen. Vor allem muß man dann nicht mit zwei Popups umgehen.
#31: Ja macht Sinn, dann geht dort mehr.
#32: Aus meiner Sicht stelle ich das auf englisch um -> konsequent. Ich hatte mir dazu wenig Gedanken gemacht, sondern nur etwas eingetragen.

Ich werden jetzt einmal die Version 2 fertig machen (ohne die eben diskutierten Extensions), damit das Text Thema, die Listen usw. fix sind. Wenn Du da ebenfalls mein reinsehen kannst (vor allem wegen der Reihenfolge im Dict (das habe ich nicht verstanden). Danach dann mal mit dem "Expertenmodus" weiter in einer Zusatzzeile.

**Comment by bgewehr** [comment]
Verstehe ich Dich richtig: 
Version 2 ist ohne den Experten-Kram, aber wieder für alle verwendbar?
Danach dann - als Vorbereitung auf Version 3 - den ganzen Eperten-Kram erarbeiten?

**Comment by mworion** [comment]
Ja, richtig verstanden. Die Version 2.0RC1 auf develop ist alles drin bis auf den experten Kram. Wenn Du was testen willst, dann diese.
Experten Kram ist auf feature branch v2.1

**Comment by bgewehr** [comment]
2.0RC1 läuft bei mir wie erwartet.

**Comment by mworion** [comment]
Gut, danke. Wenn Dir noch etwas auffällt in Bezug auf die gespeicherten daten usw. bitte Feedback.

**Comment by bgewehr** [comment]
Ein fällt mir auf: früher passte sich die Breite des Popups beim Drehen des Bildschirms auf dem iPhone an und es sah auch auf dem Handy super aus. Das ist jetzt weg, die Breite bleibt beim Drehen von Portrait zu Landscape gleicht und es ist auch im Querformat kaum bedienbar! Kannst Du danach noch mal schauen?

**Comment by mworion** [comment]
Ja, schaue ich mir nochmal an. Spontan aber keine Änderung gemacht, aber der Teufel steck da im Detail.

**Comment by bgewehr** [comment]
Also, ich kann Dir nicht sagen, warum, aber jetzt geht die Erweiterung beim Formatwechsel wieder tadellos... Komisch! Aber egal-Hauptsache geht!

**Comment by mworion** [comment]
Hallo Bernd,

ich habe das ganze im Feature Branch jetzt mal auf Experte umgestellt. Schau Dir das mal an. Danke !

**Comment by bgewehr** [comment]
Sieht sehr schön aus! Toll gemacht!
Habe mal zu testen begonnen:
1. Fall: nur Zeit
![2015-03-17 19_35_54-buro](https://cloud.githubusercontent.com/assets/4056277/6694819/f4e69f22-ccdc-11e4-8d85-137b4fd3745c.png)

führt zu

    {"active":true,"list":[{"value":"On","time":"20:00","rrule":"FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR","active":true},{"rrule":"FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR","time":"21:00","value":"Off","active":true}]}

Also alles richtig!

2. Fall: nur Sunrise
![2015-03-17 19_37_37-buro](https://cloud.githubusercontent.com/assets/4056277/6694837/1adb7c66-ccdd-11e4-99a2-d53b0d254996.png)

führt zu

    	
{"active":true,"list":[{"value":"On","time":"20:00","rrule":"FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR","active":true},{"rrule":"FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR","time":"21:00","value":"Off","active":true}]}

Hier hätte ich statt der Zeiten den Text Sunrise/Sunset erwartet!

3. Fall: Sunrise nur mit not earlier
![2015-03-17 19_40_38-buro](https://cloud.githubusercontent.com/assets/4056277/6694904/93c1ca54-ccdd-11e4-9440-8c904412f6f7.png)


führt zu

    	
{"active":true,"list":[{"rrule":"FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR","time":"20:00","value":"On","active":true},{"value":"Off","time":"21:00","rrule":"FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR","active":true}]}

Mache ich was falsch?

**Comment by bgewehr** [comment]
Habe mir grade mal den Code angesehen, kann es sein, das die function uzsuSaveTable noch gar nicht die Elemente zusammensetzt?

**Comment by bgewehr** [comment]
Wenn ich das Spiel mit createexpert und delexpert und collapsetimestring richtig deute, dann fällt mir auf, dass es evtl. zu kompliziert ist, die Expert html-Zeile dynamisch zu erzeugen und dynamisch zu vernichten und das Ergebnis in einem String zwischenzuspeichern. 

Wäre es nicht einfacher möglich, die Zeilen immer doppelt anzulegen (std und expert) aber die Zeile Exp zunächst als hidden zu formatieren (per CSS zum Beispiel http://www.w3schools.com/css/css_display_visibility.asp) und dann per Expert Button nur per CSS Klasse auf show zu setzen? Dann könnte die ganz normale Routine durch die Inhalte loopen und die ganz normalen Dinge damit tun ohne dass man erst collapsetime parsen, Zeile erzeugen, ändern, parsen collapsen und vernichten muss.

Was meinst Du?

**Comment by mworion** [comment]
Hallo Bernd,

Gute Idee mit dem hidden. Anfangs wollte ich nur eine Zeile gleichzeitig zulassen, und da ich schon diese Lösung hatte, dann einfach wiederverwendet. Ich probiere es mal aus. Das mit dem abspeichern muss ich mir noch anschauen, war erst mal nicht der Focus.

Michel

**Comment by mworion** [comment]
Du verwendest Chrome als Browser, richtig?

**Comment by bgewehr** [comment]
Ja, Chrome und IE und mobile Safari.

"Das mit dem Abspeichern" - meinst Du damit, den Sunrise String zu bilden? Oder was anderes? Ich wollte nur vorschlagen, nichts in collapsetimestring zwischenzuspeichern und dann nochmal umzuwandeln...

**Comment by bgewehr** [comment]
Eins habe ich noch für usability: was hältst Du von +/- minutes an Stelle von Offset? Das versteht dann sicher jeder und macht das Layout kompakter, oder?

**Comment by mworion** [comment]
Ja, der Vorschlag ist gut, machen wir so.

**Comment by bgewehr** [comment]
Ich habe noch was gefunden: solange das Event- selectmenu auf Time steht, könnte man die input fields auf disabled stellen, dann kommt keiner auf die Idee, ein Offset zum Event Time zu erfassen oder eine latest Zeit dazu...  http://wiki.selfhtml.org/wiki/HTML/Formulare/ausgrauen

**Comment by bgewehr** [comment]
Mit etwas mehr css könnte man zwei mediaqueries etablieren, die dafür sorgen, dass die buttongroup der Wochentage im Portrait Format ein multiselect selectmenu wird, dann passt die UZSU erstmalig auch in einem Smartphone ganz unverzerrt auf den Hochkant-Bildschirm... Soll ich mal forschen?

**Comment by mworion** [comment]
Ist eine gute Idee. Wenn Du das einmal probieren willst super. Bei uns im Forum hatte ich noch keine Anfrage dazu erhalten, war aber immer unschön gewesen.

**Comment by mworion** [comment]
zur Info: ich habe jetzt das release 2.0 draussen. 
damit: v2.0 ist jetzt master !
feature v2.2 ist jetzt develop v2.2
feature ist nur noch zum ausprobieren.
Patches würde ich jetzt wieder egegen develop machen

**Comment by mworion** [comment]
zu deinem beitrag #50
Habe ich jetzt in v2.3 eingebaut. allerdings geht das bei jquery mobile anders wie plain html. geht mit .textinput('disable') bzw. .texinput('enable')
Ich schaue mir auch nochmal das mit der visubility an. wenn das geht, baue ich die expertenzeile fest ein.

**Comment by bgewehr** [comment]
hier mal die Variation zwischen Controlgroup und multiple select:
https://jsfiddle.net/uvvm40Lu/1/

Müsste man immer beides erzeugen und aktualisieren und dann die Sichtbarkeit per CSS umschalten? Bin nicht ganz sicher, was der beste Weg ist.

**Comment by mworion** [comment]
zu deiner idee #44
ist jetzt in der v2.4 drin. wenig bis gar nicht getestet, aber man kann sichmal vorstellen, wie siech das dann anfühlt. ich muß noch einige umbauen, weil das Ganze ja in den standard reinkommt

**Comment by mworion** [comment]
hallo, das fiddle sieht so gut aus.  Packe das Ganze bitte mal in ein Popup. Dann hast du wahrscheinlich nur noch die nativen Steuerelemente. Die Konsequenz wäre dann, dass die ganze schönheit weg bleibt von jquery mobile.

**Comment by bgewehr** [comment]
nur mal kurz zwischendurch: mir werden keine Nummern der Beiträge angezeigt, daher kann ich Deine Referenzen leider immer nur erraten. Wo hast Du die Nummern her?

**Comment by mworion** [comment]
Ich sehe die Nummern in meiner IDE (Eclipse). Aber mir fällt jetzt auf, dass auf Github selbst sind keine Nummern drin.

**Comment by bgewehr** [comment]
Im Popup kann offenbar das selectmenu nicht als Popup angezeigt werden, deswegen wird gar nichts angezeigt.

Nicht so im Mobile Safari, da klappt alles:
![](http://i.imgur.com/YzduNpA.jpg)

Nützt aber im Desktop Browser nichts und schmaler ist diese Variante sowieso nicht. Also verwerfe ich diese Idee mal.

**Comment by mworion** [comment]
Ok schade, war echt eine gute Idee. Für den Umbau habe ich Feature BRANCH reaktiviert, weil es ein größerer Umbau wird. Ich nehme Design type 2 heraus, den brauchen wir mit Experten nicht mehr. Damit kann wieder Code zusamm gefasst werden und das ganze wird wieder kleiner.

**Comment by mworion** [comment]
Auf dem Feature Branch ist die v2.6 in der Umsetzung des Expertenmodus. 
DesignType = 2 gibt es nicht mehr, speichern sollte mit designType = 0 gehen, nicht bei designtype = 1. 
Das Widget ist um 100 Zeilen code geschrumpft, bin aber noch nicht final durch. 
einfach mal testen.

**Comment by bgewehr** [comment]
Super, schaue ich mir an. Die disabled Felder aus 2.4 funktionieren bei mir erwartungsgemäß. Ein- und Ausblenden der expert Zeilen auch.

**Comment by bgewehr** [comment]
Ich habe noch eine Idee für die Darstellung am Smartphone:
Wenn wir nicht mahr table-Layout machen, sondern div-tables, dann könnte man die weekdays dynamisch oberhalb der anderen Felder anzeigen, einfach per mediaqueries. Das geht nur leider nicht mit tables... Ich fiddle mal was...

**Comment by mworion** [comment]
ja das ermöglich einiges. ich hatte mich bislang gescheut (einfach der Arbeit wegen) die table durch div's zu ersetzen. irgendwann muss das aber mal gemacht werden.

**Comment by bgewehr** [comment]
Zum Selectmenu im Popup gibt es offensichtlich Lösungen wie z.B. http://dev.jtsage.com/jQM-SimpleDialog/demos2/ aber die Frage ist, wieviel JQM Aufwand man treiben möchte...

**Comment by bgewehr** [comment]
2.6feature sieht gut aus, speichert aber erweiterte Daten: 

    {"active":true,"list":[{"value":"On","time":"20:00","rrule":"FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR","active":true,"event":"time","timeCron":"20:00","timeMin":"","timeMax":"","timeOffset":""},{"rrule":"FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR","time":"21:00","value":"Off","active":true,"event":"time","timeCron":"21:00","timeMin":"","timeMax":"","timeOffset":""}]}

Hast Du vorgesehen, dass diese Ausgabe so bleibt? Sie würde ja auch in Smarthome.py nicht das dictionary "brechen", weil zusätzliche key-value-päärchen ja nicht stören dürften. Für mich wäre es natürlich damit leichter, den benötigten String für fhem wieder zusammenzusetzen, also wenn das für Dich passt - für mich ist das super einfach so!

**Comment by mworion** [comment]
Hallo, das mit dem dict ist nicht richtig, ist ein Fehler, der auch nicht so bleiben soll. Ich kann nicht die Kompatibilität zum Plugin brechen. 
Wegen der anderen Lösung zu den Erweiterungen: Ich hatte mir schon einige angesehen, aber ich würde ungern das Framework erweitern. Das wird dann in der Zukunft ein riesiger Pflegeaufwand.

**Comment by mworion** [comment]
v2.7 behebt die fehlerhaften Einträge dict und zeigt bei 'sun' Funktionen beim Öffnen auch diesen Zustand (allerding ohne Experten nicht veränderbar) an. Es sollten jetzt auch sinnvolle Werte vorbesetzt sein.

**Comment by bgewehr** [comment]
Das ist doch aber das tolle an den JSON Strings: Wenn Du was dranhängst, macht es allen Beteiligten gar nichts aus, solange die erwarteten key:value Päärchen noch drin sind. Probier das mal aus, das macht dem py bestimmt gar nichts aus! Wäre für mich erheblich einfacher, die Rohdaten zu bekommen. In time renderst Du die Zeit py sh.py wie Du sie brauchst, hinten hängen die Rohdaten einfach mit dran, was ja keinen stört...

**Comment by bgewehr** [comment]
Das ist doch aber das tolle an den JSON Strings: Wenn Du was dranhängst, macht es allen Beteiligten gar nichts aus, solange die erwarteten key:value Päärchen noch drin sind. Probier das mal aus, das macht dem py bestimmt gar nichts aus! Wäre für mich erheblich einfacher, die Rohdaten zu bekommen. In time renderst Du die Zeit py sh.py wie Du sie brauchst, hinten hängen die Rohdaten einfach mit dran, was ja keinen stört...

**Comment by bgewehr** [comment]
Das ist doch aber das tolle an den JSON Strings: Wenn Du was dranhängst, macht es allen Beteiligten gar nichts aus, solange die erwarteten key:value Päärchen noch drin sind. Probier das mal aus, das macht dem py bestimmt gar nichts aus! Wäre für mich erheblich einfacher, die Rohdaten zu bekommen. In time renderst Du die Zeit py sh.py wie Du sie brauchst, hinten hängen die Rohdaten einfach mit dran, was ja keinen stört...

**Comment by bgewehr** [comment]
Das ist doch aber das tolle an den JSON Strings: Wenn Du was dranhängst, macht es allen Beteiligten gar nichts aus, solange die erwarteten key:value Päärchen noch drin sind. Probier das mal aus, das macht dem py bestimmt gar nichts aus! Wäre für mich erheblich einfacher, die Rohdaten zu bekommen. In time renderst Du die Zeit py sh.py wie Du sie brauchst, hinten hängen die Rohdaten einfach mit dran, was ja keinen stört...

**Comment by mworion** [comment]
Ich lasse das mal so stehen, habe keine Argumente dagegen. Allerdings kenne ich das Plugin nicht. Aus meiner Sicht muss das sinnvoll getestet sein, da ich den Type selbst erweitere. Da gibt es dann kein Zurück mehr, denn nach dem ersten Aufruf stehen die Daten drin. Ich gehe davon aus, dass Du dann auch die Parameter so übergeben willst. Richtig ?

**Comment by bgewehr** [comment]
Nicht, dass wir uns missverstehen. Ich spreche nicht von einem Plugin, sondern nur von der Erweiterung des JSON Strings im Output!

**Comment by mworion** [comment]
Da sind wir schon einer Meinung. Eigentlich sollte nichts passieren, wenn alle das so realisiert haben. Das muß man mal im Plugin nachsehen (nicht umbauen).

**Comment by mworion** [comment]
hallo ich habe es jetzt mal im code dringelassen und warte mal ab, ob fehlermeldungen reinkommen !
da der thread mittlerweile lang ist, mache ich das thema jetzt mal zu, denn der request is ja erledigt.
fehlermeldungen wieder neu anlegen !

**Comment by bgewehr** [comment]
Also, ich habe noch eine Fehlermeldung, komme noch nicht dahinter, was Sache ist:

    Uncaught TypeError: Cannot read property 'indexOf' of undefinedbase.js:532 widget.explodeVM13590:619 (anonymous function)jquery-2.0.3.min.js:5 x.event.dispatchjquery-2.0.3.min.js:5 x.event.add.y.handle

**Comment by bgewehr** [comment]
Sorry, Versionsdurcheinander! Alles läuft...

**Comment by bgewehr** [comment]
WOW! Ich habe 2.85 in zehn Minuten dazu gebracht, mit fhem zusammen zu arbeiten und dies hier völlig korrekt auszuspucken:

    REV_1 en MO,TU,WE,TH,FR,SA,SU|{sunrise_abs("REAL",300,"06:00","09:00")}|On MO,TU,WE,TH,FR,SA,SU|{sunset_abs("REAL",0,"18:00","21:00")}|Off

**Comment by mworion** [comment]
Hat Spaß gemacht !
